import { useState, type ReactNode } from 'react'
import { AppIcon } from '../AppIcon'
import { SleepTimerControl, type SleepTimerValue } from '../audiobooks/SleepTimerControl'
import { BBButton, BBEmptyState, BBInput, BBLoadingIndicator, BBMediaArtwork, BBSelect, BBSurface, StatusBadge } from '../components'

type ReviewStatus = 'EXPERIMENTELL' | 'OWNER GODKÄND' | 'RATAD'
const sections = ['Foundations', 'Actions', 'Navigation', 'Cards & surfaces', 'Forms', 'Feedback', 'Media'] as const

function Specimen({ children, description, name, state = 'Default', status = 'EXPERIMENTELL' }: { children: ReactNode; description?: string; name: string; state?: string; status?: ReviewStatus }) {
  const identity = `${name} / ${state}`
  return <BBSurface aria-labelledby={`specimen-${identity.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`} className="ux-lab-specimen"><header><div><h3 id={`specimen-${identity.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`}>{name}</h3><small>{state}</small></div><span className={`ux-review-status ux-review-status--${status === 'RATAD' ? 'rejected' : status === 'OWNER GODKÄND' ? 'approved' : 'experimental'}`}>{status}</span></header>{description && <p>{description}</p>}<div className="ux-lab-specimen__stage">{children}</div></BBSurface>
}

function Section({ children, id, title }: { children: ReactNode; id: string; title: string }) { return <section aria-labelledby={`${id}-heading`} className="ux-lab-section" id={id}><h2 id={`${id}-heading`}>{title}</h2><div className="ux-lab-grid">{children}</div></section> }

export function UXLab() {
  const [pressed, setPressed] = useState(false)
  const [timer, setTimer] = useState<string | null>(null)
  const back = () => { window.history.pushState({}, '', '/'); window.dispatchEvent(new Event('bb:navigation')) }
  const setMinutes = (minutes: SleepTimerValue) => setTimer(`${minutes} min`)
  return <main className="main bb-page dashboard-workspace ux-lab" id="admin"><header className="ux-lab__header"><BBButton onClick={back} variant="tertiary">‹ Admin</BBButton><p className="eyebrow">Intern ägargranskning</p><h1>UX/UI-labb</h1><p>Verkliga produktionskomponenter och säkra lokala tillstånd. Design System v1: <strong>OWNER REVIEW IN PROGRESS</strong>.</p></header><nav aria-label="Labbkategorier" className="ux-lab__categories">{sections.map(section => { const href = `#${section.toLowerCase().replace(/[^a-z]+/g, '-')}`; return <a href={href} key={section}>{section}</a> })}</nav>
    <Section id="foundations" title="Foundations"><Specimen name="Foundations / Color & material"><div className="ux-token-swatches"><span className="ux-token-swatch ux-token-swatch--canvas">Canvas</span><span className="ux-token-swatch ux-token-swatch--surface">Surface</span><span className="ux-token-swatch ux-token-swatch--accent">Accent</span><span className="ux-token-swatch ux-token-swatch--danger">Danger</span></div></Specimen><Specimen name="Foundations / Typography"><div className="ux-type-sample"><span className="eyebrow">Eyebrow / Label</span><h1>Page title</h1><h2>Section title</h2><p>Body text för löpande innehåll.</p><small className="muted">Metadata / muted text</small></div></Specimen></Section>
    <Section id="actions" title="Actions"><Specimen name="Actions / Button"><div className="ux-lab-row"><BBButton variant="primary">Primary</BBButton><BBButton variant="secondary">Secondary</BBButton><BBButton variant="tertiary">Tertiary</BBButton><BBButton variant="danger">Destructive</BBButton></div></Specimen><Specimen name="Actions / Button" state="Disabled & loading"><div className="ux-lab-row"><BBButton disabled>Disabled</BBButton><BBButton busy>Loading</BBButton></div></Specimen><Specimen name="Actions / Button" state="Pressed"><BBButton aria-pressed={pressed} onClick={() => setPressed(value => !value)}>{pressed ? 'Active' : 'Default'}</BBButton></Specimen><Specimen name="Actions / Icon Button"><BBButton aria-label="Sök" variant="icon"><AppIcon name="search" /></BBButton></Specimen></Section>
    <Section id="navigation" title="Navigation"><Specimen name="Navigation / Row"><BBButton className="ux-navigation-row" variant="contextual"><AppIcon name="admin" /><span><strong>Öppna objekt</strong><small>Nästa hierarkinivå</small></span><AppIcon name="chevron" /></BBButton></Specimen><Specimen name="Navigation / Back"><BBButton variant="tertiary">‹ Tillbaka</BBButton></Specimen></Section>
    <Section id="cards-surfaces" title="Cards & surfaces"><Specimen name="Card / Surface"><BBSurface className="ux-inner-surface"><strong>Ordinary surface</strong><p>Delad BBSurface.</p></BBSurface></Specimen><Specimen name="Card / Interactive"><BBButton className="ux-navigation-row" variant="contextual"><span><strong>Whole object card</strong><small>Hela objektet är navigationsmål.</small></span><AppIcon name="chevron" /></BBButton></Specimen></Section>
    <Section id="forms" title="Forms"><Specimen name="Form / Text Input"><label className="bb-field">Namn<BBInput placeholder="Skriv något" /></label></Specimen><Specimen name="Form / Search Input"><label className="bb-field">Sök<BBInput type="search" placeholder="Sök i BigBrain" /></label></Specimen><Specimen name="Form / Select"><label className="bb-field">Tema<BBSelect defaultValue="obsidian"><option value="obsidian">Obsidian Gold</option><option>Forest Night</option><option>Arctic Wind</option></BBSelect></label></Specimen><Specimen description="Lokalt återkommande mönster; ännu ingen delad primitiv." name="Form / Checkbox"><label><input type="checkbox" /> Visa alternativ</label></Specimen><Specimen name="Form / Range"><input aria-label="Exempelposition" defaultValue="35" max="100" type="range" /></Specimen></Section>
    <Section id="feedback" title="Feedback"><Specimen name="Feedback / Loading"><BBLoadingIndicator label="Laddar exempel" /></Specimen><Specimen name="Feedback / Empty"><BBEmptyState detail="Det finns inget att visa i exemplet." title="Tomt läge" /></Specimen><Specimen name="Feedback / Error"><p className="notice notice--error" role="alert">Något gick fel.</p></Specimen><Specimen name="Feedback / Warning"><p className="notice notice--warning">Kontrollera detta.</p></Specimen><Specimen name="Feedback / Status"><div className="ux-lab-row"><StatusBadge status="Available" /><StatusBadge status="Unavailable" /></div></Specimen></Section>
    <Section id="media" title="Media"><Specimen name="Media / Artwork"><div className="ux-artwork-pair"><BBMediaArtwork alt="Representativt omslag" /><BBMediaArtwork alt="Omslag saknas" /></div></Specimen><Specimen name="Media / Sleep Timer / Trigger" state="Candidate"><div className="ux-timer-demo"><SleepTimerControl active={timer !== null} compact label="Öppna sovtimerkandidat" onCancel={() => setTimer(null)} onClock={clock => setTimer(clock)} onMinutes={setMinutes} />{timer && <span aria-live="polite">Aktiv: {timer}</span>}</div></Specimen><Specimen name="Media / Sleep Timer / Previous trigger & menu" state="Design direction" status="RATAD"><p>Den lilla vita klockan och den breda formulärliknande disclosure-menyn är ratade. De återges inte.</p></Specimen><Specimen name="Media / Audiobook / Library Card" state="Candidate"><BBButton className="ux-audiobook-card" variant="tertiary"><BBMediaArtwork alt="Representativt lokalt omslag" /><span><strong>Exempelboken</strong><small>Författarnamn</small></span></BBButton></Specimen></Section>
  </main>
}
