import { createContext, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { startAudiobookPlayback, syncAudiobookPlayback } from '../api'
import { BBButton, BBMediaArtwork, BBSurface } from '../components'
import type { AudiobookItem, AudiobookPlaybackSession, AudiobookPlaybackTrack } from '../types'

type PlaybackContextValue={item:AudiobookItem|null;session:AudiobookPlaybackSession|null;currentTime:number;duration:number;playing:boolean;expanded:boolean;start:(item:AudiobookItem)=>Promise<void>;toggle:()=>Promise<void>;seek:(time:number)=>Promise<void>;jump:(seconds:number)=>Promise<void>;stop:()=>Promise<void>;setExpanded:(value:boolean)=>void}
const PlaybackContext=createContext<PlaybackContextValue|null>(null)
const format=(seconds:number)=>{const safe=Math.max(0,Math.floor(seconds||0));const h=Math.floor(safe/3600);const m=Math.floor((safe%3600)/60);const s=safe%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}

export function AudiobookPlaybackProvider({children}:{children:ReactNode}){
  const audio=useRef<HTMLAudioElement|null>(null);const lastSync=useRef(0);const listenedSinceSync=useRef(0);const lastTick=useRef<number|null>(null)
  const[item,setItem]=useState<AudiobookItem|null>(null);const[session,setSession]=useState<AudiobookPlaybackSession|null>(null);const[currentTime,setCurrentTime]=useState(0);const[playing,setPlaying]=useState(false);const[expanded,setExpanded]=useState(false);const[track,setTrack]=useState<AudiobookPlaybackTrack|null>(null)
  const duration=session?.duration??item?.durationSeconds??0
  const sessionRef=useRef(session);const trackRef=useRef(track);const durationRef=useRef(duration);sessionRef.current=session;trackRef.current=track;durationRef.current=duration
  const position=()=>trackRef.current?(trackRef.current.startOffset+(audio.current?.currentTime??0)):currentTime
  const chooseTrack=(value:number,tracks=session?.tracks??[])=>tracks.find((candidate,index)=>value>=candidate.startOffset&&value<(candidate.startOffset+candidate.duration)||(index===tracks.length-1&&value>=candidate.startOffset))??tracks[0]
  const loadTrack=async(next:AudiobookPlaybackTrack,value:number,autoPlay:boolean)=>{const element=audio.current;if(!element)return;trackRef.current=next;setTrack(next);element.src=next.streamUrl;element.currentTime=Math.max(0,value-next.startOffset);element.load();if(autoPlay)await element.play()}
  const start=async(nextItem:AudiobookItem)=>{const next=await startAudiobookPlayback(nextItem.id);setItem(nextItem);setSession(next);setCurrentTime(next.currentTime);setExpanded(true);const selected=chooseTrack(next.currentTime,next.tracks);if(selected)await loadTrack(selected,next.currentTime,true)}
  const toggle=async()=>{if(!audio.current)return;if(audio.current.paused)await audio.current.play();else audio.current.pause()}
  const seek=async(value:number)=>{if(!session)return;const bounded=Math.max(0,Math.min(value,duration));const next=chooseTrack(bounded);if(!next)return;const wasPlaying=!!audio.current&&!audio.current.paused;if(track?.index===next.index&&audio.current)audio.current.currentTime=bounded-next.startOffset;else await loadTrack(next,bounded,wasPlaying);setCurrentTime(bounded)}
  const sync=async(close=false)=>{const active=sessionRef.current;if(!active)return;const now=position();const listened=Math.min(300,listenedSinceSync.current);listenedSinceSync.current=0;lastSync.current=Date.now();await syncAudiobookPlayback(active.id,now,durationRef.current,listened,close).catch(()=>undefined)}
  const stop=async()=>{audio.current?.pause();await sync(true);audio.current?.removeAttribute('src');audio.current?.load();sessionRef.current=null;trackRef.current=null;setSession(null);setTrack(null);setItem(null);setExpanded(false)}
  useEffect(()=>{const element=new Audio();element.preload='metadata';audio.current=element;const time=()=>{const now=performance.now();if(!element.paused&&lastTick.current!==null)listenedSinceSync.current+=Math.max(0,(now-lastTick.current)/1000);lastTick.current=now;const value=position();setCurrentTime(value);if(Date.now()-lastSync.current>15000)void sync()};const play=()=>{lastTick.current=performance.now();setPlaying(true)};const pause=()=>{setPlaying(false);void sync()};const ended=()=>{const active=sessionRef.current;if(!active)return;const tracks=active.tracks;const index=tracks.findIndex(value=>value.index===trackRef.current?.index);if(index>=0&&index<tracks.length-1)void loadTrack(tracks[index+1],tracks[index+1].startOffset,true);else{setPlaying(false);void sync(true)}};element.addEventListener('timeupdate',time);element.addEventListener('play',play);element.addEventListener('pause',pause);element.addEventListener('ended',ended);return()=>{element.pause();element.removeEventListener('timeupdate',time);element.removeEventListener('play',play);element.removeEventListener('pause',pause);element.removeEventListener('ended',ended)}},[])
  useEffect(()=>{const page=()=>{if(document.visibilityState==='hidden')void sync()};window.addEventListener('pagehide',page);document.addEventListener('visibilitychange',page);return()=>{window.removeEventListener('pagehide',page);document.removeEventListener('visibilitychange',page)}},[session,track,duration])
  useEffect(()=>{const navigate=()=>{if(sessionRef.current)setExpanded(false)};window.addEventListener('bb:navigation',navigate);return()=>window.removeEventListener('bb:navigation',navigate)},[])
  const value=useMemo<PlaybackContextValue>(()=>({item,session,currentTime,duration,playing,expanded,start,toggle,seek,jump:(seconds)=>seek(currentTime+seconds),stop,setExpanded}),[item,session,currentTime,duration,playing,expanded,track])
  return <PlaybackContext.Provider value={value}>{children}</PlaybackContext.Provider>
}
const unavailablePlayback:PlaybackContextValue={item:null,session:null,currentTime:0,duration:0,playing:false,expanded:false,start:async()=>undefined,toggle:async()=>undefined,seek:async()=>undefined,jump:async()=>undefined,stop:async()=>undefined,setExpanded:()=>undefined}
export function useAudiobookPlayback(){return useContext(PlaybackContext)??unavailablePlayback}

export function AudiobookPlayer(){const player=useAudiobookPlayback();if(!player.item||!player.session)return null;return <BBSurface aria-label={`Spelar ${player.item.title}`} className={`audiobook-player ${player.expanded?'audiobook-player--expanded':''}`} role="region"><button aria-label={`Öppna spelaren för ${player.item.title}`} className="audiobook-player__identity" onClick={()=>player.setExpanded(true)} type="button"><BBMediaArtwork alt="" src={player.item.coverUrl??undefined}/><span><strong>{player.item.title}</strong>{player.item.author&&<small>{player.item.author}</small>}</span></button>{player.expanded&&<><BBButton aria-label="Minimera spelaren" className="audiobook-player__close" onClick={()=>player.setExpanded(false)} variant="tertiary">⌄</BBButton><BBButton onClick={()=>void player.stop()} variant="tertiary">Stäng spelaren</BBButton></>}<div className="audiobook-player__controls"><BBButton aria-label="Hoppa bakåt 30 sekunder" onClick={()=>void player.jump(-30)} variant="tertiary">−30</BBButton><BBButton aria-label={player.playing?'Pausa ljudboken':'Spela ljudboken'} aria-pressed={player.playing} onClick={()=>void player.toggle()} variant="secondary">{player.playing?'Paus':'Spela'}</BBButton><BBButton aria-label="Hoppa framåt 30 sekunder" onClick={()=>void player.jump(30)} variant="tertiary">+30</BBButton></div><label className="audiobook-player__timeline"><span className="sr-only">Position i ljudboken</span><input aria-valuemax={Math.round(player.duration)} aria-valuemin={0} aria-valuenow={Math.round(player.currentTime)} max={player.duration||1} min="0" onChange={event=>void player.seek(Number(event.target.value))} step="1" type="range" value={Math.min(player.currentTime,player.duration||1)}/><span>{format(player.currentTime)} / {format(player.duration)}</span></label></BBSurface>}
