using System.Globalization;
using BigBrain.Modules.Finance;
using Microsoft.Data.Sqlite;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace BigBrain.Api.Finance;

internal sealed record FinanceMacroStatus(string OperatingMode,string Provider,string Availability,string EvidenceClass,string FeatureRevision,string RegimePolicy,int SeriesCount,int ObservationCount,int RevisionCount,string Rights,string Retention,string? LatestRevision);
internal sealed record FinanceMacroSnapshot(FinanceMacroStatus Status,IReadOnlyList<MacroSeriesDefinition> Series,IReadOnlyList<MacroObservation> Observations,MarketRegime? LatestRegime);
internal sealed record RegimeAnalysisBucket(string Composite,int Sessions,decimal Return,decimal MaximumDrawdown,string EvidenceWarning);
internal sealed record RegimeAnalysisRun(string RunId,string StrategyId,string StrategyVersion,string MacroRevision,string FeatureRevision,string RegimePolicy,string EvidenceClass,IReadOnlyList<RegimeAnalysisBucket> Regimes);
internal sealed record FinanceRegimeAnalysis(string OperatingMode,string Classification,IReadOnlyList<RegimeAnalysisRun> Runs,string Limitation);

internal sealed class FinanceMacroMemory
{
    private readonly string _connection;
    internal FinanceMacroMemory(EodhdFinanceOptions options){var directory=Path.GetDirectoryName(Path.GetFullPath(options.DatabasePath));if(directory is not null)Directory.CreateDirectory(directory);_connection=new SqliteConnectionStringBuilder{DataSource=options.DatabasePath}.ToString();Initialize();}
    private void Initialize(){using var c=new SqliteConnection(_connection);c.Open();using var x=c.CreateCommand();x.CommandText="""
      CREATE TABLE IF NOT EXISTS finance_schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_utc TEXT NOT NULL);
      INSERT OR IGNORE INTO finance_schema_migrations VALUES(90,'BB-090 macro memory foundation',datetime('now'));
      CREATE TABLE IF NOT EXISTS macro_revisions(revision_id TEXT PRIMARY KEY,provider TEXT NOT NULL,artifact_hash TEXT NOT NULL,created_utc TEXT NOT NULL,evidence_class TEXT NOT NULL,quality_result TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS macro_observations(revision_id TEXT NOT NULL,series_id TEXT NOT NULL,reference_period TEXT NOT NULL,value TEXT,knowledge_time_utc TEXT NOT NULL,acquired_utc TEXT NOT NULL,realtime_start TEXT NOT NULL,realtime_end TEXT NOT NULL,artifact_hash TEXT NOT NULL,evidence_class TEXT NOT NULL,PRIMARY KEY(revision_id,series_id,reference_period,knowledge_time_utc));
      """;x.ExecuteNonQuery();}
    internal string Promote(IEnumerable<MacroObservation> input)
    {
        var rows=input.OrderBy(x=>x.SeriesId).ThenBy(x=>x.ReferencePeriod).ThenBy(x=>x.KnowledgeTimeUtc).ToArray();Validate(rows);var hash=MacroFeatureEngine.Hash(rows);var id="fred-"+hash[7..23];using var c=new SqliteConnection(_connection);c.Open();using var t=c.BeginTransaction();Exec(c,t,"INSERT OR IGNORE INTO macro_revisions VALUES($id,'FRED',$hash,$at,$class,'PASS')",("$id",id),("$hash",hash),("$at",DateTimeOffset.UtcNow.ToString("O",CultureInfo.InvariantCulture)),("$class",rows[0].EvidenceClass.ToString()));
        foreach(var r in rows)Exec(c,t,"INSERT OR IGNORE INTO macro_observations VALUES($revision,$series,$period,$value,$knowledge,$acquired,$start,$end,$hash,$class)",("$revision",id),("$series",r.SeriesId),("$period",r.ReferencePeriod.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$value",r.Value is null?(object)DBNull.Value:r.Value.Value.ToString(CultureInfo.InvariantCulture)),("$knowledge",r.KnowledgeTimeUtc.ToString("O",CultureInfo.InvariantCulture)),("$acquired",r.AcquiredAtUtc.ToString("O",CultureInfo.InvariantCulture)),("$start",r.RealtimeStart.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$end",r.RealtimeEnd.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$hash",r.ArtifactHash),("$class",r.EvidenceClass.ToString()));t.Commit();return id;
    }
    internal FinanceMacroSnapshot Snapshot()
    {
        using var c=new SqliteConnection(_connection);c.Open();var rows=new List<MacroObservation>();
        using(var x=c.CreateCommand()){x.CommandText="SELECT series_id,reference_period,value,knowledge_time_utc,acquired_utc,realtime_start,realtime_end,artifact_hash,evidence_class FROM macro_observations ORDER BY series_id,reference_period,knowledge_time_utc";using var r=x.ExecuteReader();while(r.Read())rows.Add(new MacroObservation(r.GetString(0),DateOnly.Parse(r.GetString(1),CultureInfo.InvariantCulture),r.IsDBNull(2)?null:decimal.Parse(r.GetString(2),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(3),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(4),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(5),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(6),CultureInfo.InvariantCulture),r.GetString(7),Enum.Parse<MacroEvidenceClass>(r.GetString(8))));}
        var revision=Scalar(c,"SELECT revision_id FROM macro_revisions ORDER BY created_utc DESC LIMIT 1");var status=new FinanceMacroStatus("RESEARCH","FRED",rows.Count==0?"BOOTSTRAPPING":"AVAILABLE",rows.Count==0?"UNAVAILABLE":rows[0].EvidenceClass.ToString(),FredMacroPackV1.FeatureRevision,FredMacroPackV1.RegimePolicy,FredMacroPackV1.Series.Count,rows.Count,Convert.ToInt32(Scalar(c,"SELECT CAST(COUNT(*) AS TEXT) FROM macro_revisions")??"0",CultureInfo.InvariantCulture),"Public domain: citation requested; series-specific rights checked","Normalized observations and provenance retained; revalidate terms before redistribution",revision);MarketRegime? regime=null;if(rows.Count>0&&revision is not null){var cutoff=rows.Max(x=>x.KnowledgeTimeUtc);var session=rows.Max(x=>x.ReferencePeriod);regime=MacroFeatureEngine.Regime(session,cutoff,MacroFeatureEngine.At(session,cutoff,rows,revision),revision,rows[0].EvidenceClass);}return new(status,FredMacroPackV1.Series,rows.TakeLast(100).ToArray(),regime);
    }
    internal FinanceRegimeAnalysis Analyze(EodhdMarketMemory market)
    {
        var snapshot=Snapshot();if(snapshot.Status.LatestRevision is null)return new("RESEARCH","UNAVAILABLE",[],"Macro Memory is bootstrapping.");using var c=new SqliteConnection(_connection);c.Open();var all=new List<MacroObservation>();using(var x=c.CreateCommand()){x.CommandText="SELECT series_id,reference_period,value,knowledge_time_utc,acquired_utc,realtime_start,realtime_end,artifact_hash,evidence_class FROM macro_observations";using var r=x.ExecuteReader();while(r.Read())all.Add(new(r.GetString(0),DateOnly.Parse(r.GetString(1),CultureInfo.InvariantCulture),r.IsDBNull(2)?null:decimal.Parse(r.GetString(2),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(3),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(4),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(5),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(6),CultureInfo.InvariantCulture),r.GetString(7),Enum.Parse<MacroEvidenceClass>(r.GetString(8))));}
        var cutoff=all.Max(x=>x.KnowledgeTimeUtc);var runs=new List<RegimeAnalysisRun>();foreach(var summary in market.BacktestCatalog().Runs){var result=market.BacktestResult(summary.RunId);if(result is null||result.EquityCurve.Count<2)continue;var points=result.EquityCurve.Zip(result.EquityCurve.Skip(1),(a,b)=>(a,b,ret:a.TotalEquity==0?0:b.TotalEquity/a.TotalEquity-1)).Select(x=>(x.b.Session,x.ret,regime:MacroFeatureEngine.Regime(x.b.Session,cutoff,MacroFeatureEngine.At(x.b.Session,cutoff,all,snapshot.Status.LatestRevision),snapshot.Status.LatestRevision,FredMacroPackV1.Series.Count>0?all[0].EvidenceClass:MacroEvidenceClass.RevisedHistoryExploratory))).GroupBy(x=>x.regime.Composite).Select(g=>{decimal cumulative=0,peak=1,maxDrawdown=0;foreach(var p in g.OrderBy(x=>x.Session)){cumulative=(1+cumulative)*(1+p.ret)-1;peak=Math.Max(peak,1+cumulative);maxDrawdown=Math.Min(maxDrawdown,(1+cumulative)/peak-1);}return new RegimeAnalysisBucket(g.Key,g.Count(),cumulative,maxDrawdown,g.Count()<20?"INSUFFICIENT_SAMPLE":"Observed result; no significance claim.");}).OrderBy(x=>x.Composite,StringComparer.Ordinal).ToArray();runs.Add(new(summary.RunId,summary.StrategyId,summary.StrategyVersion,snapshot.Status.LatestRevision,FredMacroPackV1.FeatureRevision,FredMacroPackV1.RegimePolicy,all[0].EvidenceClass.ToString(),points));}return new("RESEARCH",all[0].EvidenceClass.ToString(),runs,"Regime grouping analyzes existing runs; it does not change strategy logic. Revised-history evidence is not point-in-time causal.");
    }
    private static void Validate(MacroObservation[] rows){if(rows.Length==0)throw new InvalidDataException("Macro candidate is empty.");var allowed=FredMacroPackV1.Series.Select(x=>x.SeriesId).ToHashSet();if(rows.Any(x=>!allowed.Contains(x.SeriesId)||x.KnowledgeTimeUtc.Offset!=TimeSpan.Zero||x.AcquiredAtUtc.Offset!=TimeSpan.Zero||x.KnowledgeTimeUtc>x.AcquiredAtUtc||x.Value is decimal v&&(v<-10000||v>100000)))throw new InvalidDataException("Macro candidate failed identity, time or numeric validation.");if(rows.GroupBy(x=>(x.SeriesId,x.ReferencePeriod,x.KnowledgeTimeUtc)).Any(x=>x.Count()>1))throw new InvalidDataException("Macro candidate contains duplicate knowledge-time observations.");}
    private static void Exec(SqliteConnection c,SqliteTransaction t,string sql,params(string,object)[] args){using var x=c.CreateCommand();x.Transaction=t;x.CommandText=sql;foreach(var a in args)x.Parameters.AddWithValue(a.Item1,a.Item2);x.ExecuteNonQuery();}
    private static string? Scalar(SqliteConnection c,string sql){using var x=c.CreateCommand();x.CommandText=sql;return x.ExecuteScalar() as string;}
}

internal static class FinanceMacroMaintenanceCommand
{
    internal static bool TryRun(string[] args,IConfiguration configuration)
    {
        if(args.Length==0||args[0]!="finance-macro-promote")return false;
        if(args.Length!=6)throw new ArgumentException("Use finance-macro-promote <DFF.csv> <DGS2.csv> <DGS10.csv> <CPIAUCSL.csv> <UNRATE.csv>.");
        var expected=FredMacroPackV1.Series.Select(x=>x.SeriesId).ToHashSet(StringComparer.Ordinal);var acquired=new DateTimeOffset(DateOnly.FromDateTime(DateTime.UtcNow).ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);var observations=new List<MacroObservation>();
        foreach(var path in args.Skip(1)){var id=Path.GetFileNameWithoutExtension(path).ToUpperInvariant();if(!expected.Remove(id))throw new InvalidDataException("Unexpected or duplicate FRED series artifact.");var bytes=File.ReadAllBytes(path);var hash="sha256:"+Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();using var reader=new StringReader(Encoding.UTF8.GetString(bytes));var header=reader.ReadLine()?.Trim();if(header!=$"observation_date,{id}"&&header!=$"DATE,{id}")throw new InvalidDataException($"Unexpected FRED CSV schema for {id}.");string? line;while((line=reader.ReadLine()) is not null){var parts=line.Split(',');if(parts.Length!=2||!DateOnly.TryParseExact(parts[0],"yyyy-MM-dd",CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.None,out var period))throw new InvalidDataException($"Malformed FRED row for {id}.");decimal? value=string.IsNullOrWhiteSpace(parts[1])||parts[1]=="."?null:decimal.TryParse(parts[1],System.Globalization.NumberStyles.Float,CultureInfo.InvariantCulture,out var parsed)?parsed:throw new InvalidDataException($"Malformed FRED value for {id}.");observations.Add(new(id,period,value,acquired,acquired,new DateOnly(2026,8,16),new DateOnly(9999,12,31),hash,MacroEvidenceClass.RevisedHistoryExploratory));}}
        if(expected.Count>0)throw new InvalidDataException("FRED pack is incomplete.");var options=configuration.GetSection(EodhdFinanceOptions.Section).Get<EodhdFinanceOptions>()??new();var memory=new FinanceMacroMemory(options);var revision=memory.Promote(observations);Console.WriteLine(JsonSerializer.Serialize(new{revision,series=5,observations=observations.Count,classification="REVISED_HISTORY_EXPLORATORY",acquiredAtUtc=acquired,regime=memory.Snapshot().LatestRegime}));return true;
    }
}
