using System.Globalization;
using BigBrain.Modules.Finance;
using Microsoft.Data.Sqlite;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

#pragma warning disable CS8602 // Candidate file identity is validated immediately after extraction.
#pragma warning disable CA1859 // Interface return types document bounded pipeline contracts.

namespace BigBrain.Api.Finance;

public sealed record FinanceFredOptions
{
    public const string Section="Finance:Fred";
    public bool Enabled { get; set; }
    public string ApiKey { get; set; }="";
    public string BaseUrl { get; set; }="https://api.stlouisfed.org";
    public int TimeoutSeconds { get; set; }=30;
    public int MaximumVintageObservations { get; set; }=5000;
    public string QuarantineDirectory { get; set; }=Path.Combine(Path.GetTempPath(),"bigbrain-finance","macro-quarantine");
    internal bool ApiKeyConfigured=>!string.IsNullOrWhiteSpace(ApiKey);
    internal void Validate(){if(!Uri.TryCreate(BaseUrl,UriKind.Absolute,out var uri)||uri.Scheme!=Uri.UriSchemeHttps||!string.Equals(uri.Host,"api.stlouisfed.org",StringComparison.OrdinalIgnoreCase)||TimeoutSeconds is <5 or >120||MaximumVintageObservations is <1 or >10000)throw new InvalidOperationException("FRED configuration is invalid or not first-party bounded.");}
}

internal sealed record FinanceMacroStatus(string OperatingMode,string Provider,string Availability,string EvidenceClass,string FeatureRevision,string RegimePolicy,int SeriesCount,int ObservationCount,int RevisionCount,string Rights,string Retention,string? LatestRevision,bool FredEnabled,bool FredApiKeyConfigured);
internal sealed record FinanceMacroSnapshot(FinanceMacroStatus Status,IReadOnlyList<MacroSeriesDefinition> Series,IReadOnlyList<MacroObservation> Observations,MarketRegime? LatestRegime);
internal sealed record RegimeAnalysisBucket(string Composite,int Sessions,decimal Return,decimal MaximumDrawdown,string EvidenceWarning);
internal sealed record RegimeAnalysisRun(string RunId,string StrategyId,string StrategyVersion,string MacroRevision,string FeatureRevision,string RegimePolicy,string EvidenceClass,IReadOnlyList<RegimeAnalysisBucket> Regimes);
internal sealed record FinanceRegimeAnalysis(string OperatingMode,string Classification,IReadOnlyList<RegimeAnalysisRun> Runs,string Limitation);

internal sealed class FinanceMacroMemory
{
    private readonly string _connection;
    private readonly FinanceFredOptions _fred;
    internal FinanceMacroMemory(EodhdFinanceOptions options,FinanceFredOptions? fred=null){FinanceSchemaMigrator.Migrate(options.DatabasePath);_connection=new SqliteConnectionStringBuilder{DataSource=options.DatabasePath}.ToString();_fred=fred??new();}
    internal string StageAndPromoteCsvPack(IReadOnlyList<string> paths,FinanceFredOptions options)
    {
        options.Validate();if(paths.Count==0)throw new InvalidDataException("Macro candidate is empty.");Directory.CreateDirectory(options.QuarantineDirectory);var acquired=new DateTimeOffset(DateOnly.FromDateTime(DateTime.UtcNow).ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);var expected=paths.Select(Path.GetFileNameWithoutExtension).Select(x=>x?.ToUpperInvariant()??"").Order(StringComparer.Ordinal).ToArray();var artifactHash=HashFiles(paths);var candidateId="fred-candidate-"+artifactHash[7..23];var root=Path.Combine(options.QuarantineDirectory,candidateId);Directory.CreateDirectory(root);var staged=new List<string>();foreach(var source in paths.Order(StringComparer.Ordinal)){var target=Path.Combine(root,Path.GetFileName(source));File.Copy(source,target,true);staged.Add(target);}try{if(expected.Distinct(StringComparer.Ordinal).Count()!=expected.Length||expected.Any(x=>!FredMacroPackV1.Series.Any(s=>s.SeriesId==x)))throw new InvalidDataException("Macro candidate contains an unexpected or duplicate series.");var rows=ParseFredCsv(staged,acquired,MacroEvidenceClass.RevisedHistoryExploratory);return RecordCandidateAndPromote(candidateId,"https://fred.stlouisfed.org/graph/fredgraph.csv","PublicDomainCitationRequested","https://fred.stlouisfed.org/legal/terms/",staged,artifactHash,rows,"fred-csv-v1");}catch(Exception ex) when(ex is InvalidDataException or FormatException or JsonException){RecordRejectedCandidate(candidateId,"https://fred.stlouisfed.org/graph/fredgraph.csv",staged,artifactHash,acquired,expected,ex.Message);throw;}
    }
    internal string StageAndPromoteVintage(string seriesId,byte[] json,FinanceFredOptions options,DateTimeOffset acquired)
    {
        options.Validate();if(seriesId is not ("CPIAUCSL" or "UNRATE"))throw new InvalidDataException("Vintage drill is bounded to CPIAUCSL or UNRATE.");var hash="sha256:"+Convert.ToHexString(SHA256.HashData(json)).ToLowerInvariant();var id="fred-vintage-candidate-"+hash[7..23];var root=Path.Combine(options.QuarantineDirectory,id);Directory.CreateDirectory(root);var path=Path.Combine(root,$"{seriesId}.json");File.WriteAllBytes(path,json);try{var rows=ParseVintageJson(seriesId,json,acquired,options.MaximumVintageObservations);return RecordCandidateAndPromote(id,"https://api.stlouisfed.org/fred/series/observations","PublicDomainCitationRequested","https://fred.stlouisfed.org/docs/api/terms_of_use.html",[path],hash,rows,"fred-api-vintage-json-v2");}catch(Exception ex) when(ex is InvalidDataException or FormatException or JsonException or KeyNotFoundException or InvalidOperationException){RecordRejectedCandidate(id,"https://api.stlouisfed.org/fred/series/observations",[path],hash,acquired,[seriesId],ex.Message);throw;}
    }
    internal string StageAndPromoteRiksbank(string seriesId,byte[] json,DateTimeOffset acquired,bool localResearchRights=true)
    {
        var definition=EuropeanMacroPackV1.Riksbank.SingleOrDefault(x=>x.SeriesId==seriesId)??throw new InvalidDataException("Unexpected Riksbank series.");
        return StageEuropean("RIKSBANK",seriesId,json,"json","https://api.riksbank.se/swea/v1/Observations/"+seriesId,"https://www.riksbank.se/en-gb/statistics/interest-rates-and-exchange-rates/retrieving-interest-rates-and-exchange-rates-via-api/faq--the-api-for-interest-rates-and-exchange-rates/",localResearchRights,acquired,bytes=>ParseRiksbank(seriesId,definition,bytes,acquired));
    }
    internal string StageAndPromoteEcb(string seriesId,byte[] csv,DateTimeOffset acquired,bool localResearchRights=true)
    {
        var definition=EuropeanMacroPackV1.Ecb.SingleOrDefault(x=>x.SeriesId==seriesId)??throw new InvalidDataException("Unexpected ECB series.");
        return StageEuropean("ECB",seriesId,csv,"csv","https://data-api.ecb.europa.eu/service/data/","https://www.ecb.europa.eu/stats/ecb_statistics/governance_and_quality_framework/html/usage_policy.en.html",localResearchRights,acquired,bytes=>ParseEcb(seriesId,definition,bytes,acquired));
    }
    private string StageEuropean(string provider,string seriesId,byte[] artifact,string extension,string sourceUrl,string rightsUrl,bool rightsAllowed,DateTimeOffset acquired,Func<byte[],IReadOnlyList<MacroObservation>> parse)
    {
        if(acquired.Offset!=TimeSpan.Zero||artifact.Length is 0 or >5_000_000)throw new InvalidDataException("European macro artifact boundary failed.");var hash="sha256:"+Convert.ToHexString(SHA256.HashData(artifact)).ToLowerInvariant();var candidateId=provider.ToLowerInvariant()+"-candidate-"+hash[7..23];var root=Path.Combine(_fred.QuarantineDirectory,candidateId);Directory.CreateDirectory(root);var path=Path.Combine(root,seriesId.Replace('.','_')+"."+extension);File.WriteAllBytes(path,artifact);
        if(!rightsAllowed){RecordEuropeanCandidate(candidateId,provider,sourceUrl,rightsUrl,path,hash,acquired,seriesId,"MANUAL_REVIEW","FAIL","REJECTED",null);throw new InvalidDataException("Provider rights do not permit LOCAL_RESEARCH promotion.");}using(var c=new SqliteConnection(_connection)){c.Open();using var existing=c.CreateCommand();existing.CommandText="SELECT canonical_revision_id FROM macro_candidates WHERE candidate_id=$id AND validation_result='PASS' AND promotion_decision='PROMOTED'";existing.Parameters.AddWithValue("$id",candidateId);if(existing.ExecuteScalar() is string revision)return revision;}
        try{var rows=parse(artifact);Validate(rows.ToArray());RecordEuropeanCandidate(candidateId,provider,sourceUrl,rightsUrl,path,hash,acquired,seriesId,"LOCAL_RESEARCH","PASS","APPROVED",null);var revision=Promote(rows,provider);RecordEuropeanCandidate(candidateId,provider,sourceUrl,rightsUrl,path,hash,acquired,seriesId,"LOCAL_RESEARCH","PASS","PROMOTED",revision);return revision;}
        catch(Exception ex) when(ex is InvalidDataException or FormatException or JsonException or InvalidOperationException){RecordEuropeanCandidate(candidateId,provider,sourceUrl,rightsUrl,path,hash,acquired,seriesId,"LOCAL_RESEARCH","FAIL","REJECTED",null);throw;}
    }
    private void RecordEuropeanCandidate(string id,string provider,string url,string rightsUrl,string path,string hash,DateTimeOffset acquired,string series,string rights,string validation,string decision,string? revision)
    {using var c=new SqliteConnection(_connection);c.Open();using var x=c.CreateCommand();x.CommandText="INSERT OR REPLACE INTO macro_candidates(candidate_id,provider,source_url,artifact_path,artifact_hash,acquired_utc,rights_class,rights_evidence_url,series_json,schema_fingerprint,validation_result,promotion_decision,canonical_revision_id) VALUES($id,$provider,$url,$path,$hash,$at,$rights,$rightsUrl,$series,$schema,$validation,$decision,$revision)";x.Parameters.AddWithValue("$id",id);x.Parameters.AddWithValue("$provider",provider);x.Parameters.AddWithValue("$url",url);x.Parameters.AddWithValue("$path",Path.GetFileName(path));x.Parameters.AddWithValue("$hash",hash);x.Parameters.AddWithValue("$at",acquired.ToString("O",CultureInfo.InvariantCulture));x.Parameters.AddWithValue("$rights",rights);x.Parameters.AddWithValue("$rightsUrl",rightsUrl);x.Parameters.AddWithValue("$series",JsonSerializer.Serialize(new[]{series}));x.Parameters.AddWithValue("$schema","sha256:"+Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(provider+"|"+series+"|v1"))).ToLowerInvariant());x.Parameters.AddWithValue("$validation",validation);x.Parameters.AddWithValue("$decision",decision);x.Parameters.AddWithValue("$revision",revision is null?DBNull.Value:revision);x.ExecuteNonQuery();}
    private string Promote(IEnumerable<MacroObservation> input,string provider="FRED")
    {
        var rows=input.OrderBy(x=>x.SeriesId).ThenBy(x=>x.ReferencePeriod).ThenBy(x=>x.KnowledgeTimeUtc).ToArray();Validate(rows);var hash=MacroFeatureEngine.Hash(rows);var id=provider.ToLowerInvariant()+"-"+hash[7..23];using var c=new SqliteConnection(_connection);c.Open();using var t=c.BeginTransaction();Exec(c,t,"INSERT OR IGNORE INTO macro_revisions(revision_id,provider,artifact_hash,created_utc,evidence_class,quality_result) VALUES($id,$provider,$hash,$at,$class,'PASS')",("$id",id),("$provider",provider),("$hash",hash),("$at",DateTimeOffset.UtcNow.ToString("O",CultureInfo.InvariantCulture)),("$class",rows[0].EvidenceClass.ToString()));
        foreach(var r in rows)Exec(c,t,"INSERT OR IGNORE INTO macro_observations(revision_id,series_id,reference_period,value,knowledge_time_utc,acquired_utc,realtime_start,realtime_end,artifact_hash,evidence_class,provider,region,unit,frequency,base_currency,quote_currency) VALUES($revision,$series,$period,$value,$knowledge,$acquired,$start,$end,$hash,$class,$provider,$region,$unit,$frequency,$base,$quote)",("$revision",id),("$series",r.SeriesId),("$period",r.ReferencePeriod.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$value",r.Value is null?(object)DBNull.Value:r.Value.Value.ToString(CultureInfo.InvariantCulture)),("$knowledge",r.KnowledgeTimeUtc.ToString("O",CultureInfo.InvariantCulture)),("$acquired",r.AcquiredAtUtc.ToString("O",CultureInfo.InvariantCulture)),("$start",r.RealtimeStart.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$end",r.RealtimeEnd.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$hash",r.ArtifactHash),("$class",r.EvidenceClass.ToString()),("$provider",r.Provider),("$region",r.Region.ToString()),("$unit",r.Unit),("$frequency",r.Frequency),("$base",r.BaseCurrency is null?DBNull.Value:r.BaseCurrency),("$quote",r.QuoteCurrency is null?DBNull.Value:r.QuoteCurrency));t.Commit();return id;
    }
    private string RecordCandidateAndPromote(string candidateId,string sourceUrl,string rights,string rightsUrl,IReadOnlyList<string> staged,string artifactHash,IReadOnlyList<MacroObservation> rows,string schema)
    {
        Validate(rows.ToArray());var schemaHash="sha256:"+Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(schema+"|"+string.Join('|',rows.Select(x=>x.SeriesId).Distinct().Order())))).ToLowerInvariant();using var c=new SqliteConnection(_connection);c.Open();using(var x=c.CreateCommand()){x.CommandText="INSERT OR IGNORE INTO macro_candidates VALUES($id,'FRED',$url,$path,$hash,$at,$rights,$rightsUrl,$series,$schema,'PASS','APPROVED',NULL)";x.Parameters.AddWithValue("$id",candidateId);x.Parameters.AddWithValue("$url",sourceUrl);x.Parameters.AddWithValue("$path",JsonSerializer.Serialize(staged.Select(Path.GetFileName)));x.Parameters.AddWithValue("$hash",artifactHash);x.Parameters.AddWithValue("$at",rows.Max(r=>r.AcquiredAtUtc).ToString("O",CultureInfo.InvariantCulture));x.Parameters.AddWithValue("$rights",rights);x.Parameters.AddWithValue("$rightsUrl",rightsUrl);x.Parameters.AddWithValue("$series",JsonSerializer.Serialize(rows.Select(r=>r.SeriesId).Distinct().Order()));x.Parameters.AddWithValue("$schema",schemaHash);x.ExecuteNonQuery();}var revision=Promote(rows);using(var x=c.CreateCommand()){x.CommandText="UPDATE macro_candidates SET promotion_decision='PROMOTED',canonical_revision_id=$revision WHERE candidate_id=$id AND validation_result='PASS'";x.Parameters.AddWithValue("$revision",revision);x.Parameters.AddWithValue("$id",candidateId);x.ExecuteNonQuery();}return revision;
    }
    private void RecordRejectedCandidate(string candidateId,string sourceUrl,IReadOnlyList<string> staged,string artifactHash,DateTimeOffset acquired,IReadOnlyList<string> series,string reason)
    {
        using var c=new SqliteConnection(_connection);c.Open();using var x=c.CreateCommand();x.CommandText="INSERT OR REPLACE INTO macro_candidates VALUES($id,'FRED',$url,$path,$hash,$at,'PublicDomainCitationRequested','https://fred.stlouisfed.org/docs/api/terms_of_use.html',$series,'UNVERIFIED','FAIL','REJECTED',NULL)";x.Parameters.AddWithValue("$id",candidateId);x.Parameters.AddWithValue("$url",sourceUrl);x.Parameters.AddWithValue("$path",JsonSerializer.Serialize(staged.Select(Path.GetFileName)));x.Parameters.AddWithValue("$hash",artifactHash);x.Parameters.AddWithValue("$at",acquired.ToString("O",CultureInfo.InvariantCulture));x.Parameters.AddWithValue("$series",JsonSerializer.Serialize(series));x.ExecuteNonQuery();_ = reason;
    }
    private static IReadOnlyList<MacroObservation> ParseFredCsv(IReadOnlyList<string> paths,DateTimeOffset acquired,MacroEvidenceClass evidence){var rows=new List<MacroObservation>();foreach(var path in paths){var id=Path.GetFileNameWithoutExtension(path).ToUpperInvariant();var bytes=File.ReadAllBytes(path);var hash="sha256:"+Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();using var reader=new StringReader(Encoding.UTF8.GetString(bytes));var header=reader.ReadLine()?.Trim();if(header!=$"observation_date,{id}"&&header!=$"DATE,{id}")throw new InvalidDataException($"Unexpected FRED CSV schema for {id}.");string? line;while((line=reader.ReadLine()) is not null){var parts=line.Split(',');if(parts.Length!=2||!DateOnly.TryParseExact(parts[0],"yyyy-MM-dd",CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.None,out var period))throw new InvalidDataException($"Malformed FRED row for {id}.");decimal? value=string.IsNullOrWhiteSpace(parts[1])||parts[1]=="."?null:decimal.TryParse(parts[1],System.Globalization.NumberStyles.Float,CultureInfo.InvariantCulture,out var parsed)?parsed:throw new InvalidDataException($"Malformed FRED value for {id}.");rows.Add(new(id,period,value,acquired,acquired,new(2026,8,16),new(9999,12,31),hash,evidence));}}return rows;}
    private static IReadOnlyList<MacroObservation> ParseVintageJson(string seriesId,byte[] json,DateTimeOffset acquired,int maximum)
    {
        using var doc=JsonDocument.Parse(json);var root=doc.RootElement;if(root.GetProperty("output_type").GetInt32()!=2)throw new InvalidDataException("FRED vintage response must use output_type=2.");var realtimeEnd=DateOnly.ParseExact(root.GetProperty("realtime_end").GetString()!,"yyyy-MM-dd",CultureInfo.InvariantCulture);var observations=root.GetProperty("observations");if(observations.ValueKind!=JsonValueKind.Array)throw new InvalidDataException("FRED vintage response observations must be an array.");var columns=observations.EnumerateArray().SelectMany(x=>x.EnumerateObject()).Where(x=>x.Name!="date").Select(x=>x.Name).Distinct(StringComparer.Ordinal).Select(name=>{var prefix=seriesId+"_";if(!name.StartsWith(prefix,StringComparison.Ordinal)||!DateOnly.TryParseExact(name[prefix.Length..],"yyyyMMdd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var vintage))throw new InvalidDataException("FRED vintage response contains an unexpected series/vintage column.");return(name,vintage);}).OrderBy(x=>x.vintage).ToArray();if(columns.Length==0)throw new InvalidDataException("FRED vintage response contains no vintage columns.");var hash="sha256:"+Convert.ToHexString(SHA256.HashData(json)).ToLowerInvariant();var result=new List<MacroObservation>();foreach(var item in observations.EnumerateArray()){var reference=DateOnly.ParseExact(item.GetProperty("date").GetString()!,"yyyy-MM-dd",CultureInfo.InvariantCulture);for(var i=0;i<columns.Length;i++){var column=columns[i];if(!item.TryGetProperty(column.name,out var valueElement))continue;if(result.Count>=maximum)throw new InvalidDataException("FRED vintage response exceeds bounded observation limit.");var text=valueElement.GetString()??throw new InvalidDataException("FRED vintage value must be a string.");decimal? value=text=="."?null:decimal.TryParse(text,NumberStyles.Float,CultureInfo.InvariantCulture,out var parsed)?parsed:throw new InvalidDataException("FRED vintage value is malformed.");var end=i+1<columns.Length?columns[i+1].vintage.AddDays(-1):realtimeEnd;if(end<column.vintage)throw new InvalidDataException("FRED vintage periods are not monotonic.");var knowledge=new DateTimeOffset(column.vintage.AddDays(1).ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);result.Add(new(seriesId,reference,value,knowledge,acquired,column.vintage,end,hash,MacroEvidenceClass.PointInTimeCausal));}}return result;
    }
    private static IReadOnlyList<MacroObservation> ParseRiksbank(string seriesId,MacroSeriesDefinition definition,byte[] json,DateTimeOffset acquired)
    {
        using var doc=JsonDocument.Parse(json);if(doc.RootElement.ValueKind!=JsonValueKind.Array)throw new InvalidDataException("Riksbank response must be an array.");var hash="sha256:"+Convert.ToHexString(SHA256.HashData(json)).ToLowerInvariant();var result=new List<MacroObservation>();foreach(var row in doc.RootElement.EnumerateArray()){if(!DateOnly.TryParseExact(row.GetProperty("date").GetString(),"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var date)||!row.GetProperty("value").TryGetDecimal(out var value))throw new InvalidDataException("Malformed Riksbank observation.");var fx=seriesId switch{"SEKEURPMI"=>("EUR","SEK"),"SEKUSDPMI"=>("USD","SEK"),_=>(null,null)};result.Add(new(seriesId,date,value,acquired,acquired,DateOnly.FromDateTime(acquired.UtcDateTime),new(9999,12,31),hash,MacroEvidenceClass.RevisedHistoryExploratory,"RIKSBANK",MacroRegion.Sweden,definition.Units,definition.Frequency,fx.Item1,fx.Item2));}return result;
    }
    private static IReadOnlyList<MacroObservation> ParseEcb(string expectedSeries,MacroSeriesDefinition definition,byte[] csv,DateTimeOffset acquired)
    {
        var lines=Encoding.UTF8.GetString(csv).Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries);
        if(lines.Length<2)throw new InvalidDataException("ECB CSV contains no observations.");
        var header=Csv(lines[0]);var key=Array.IndexOf(header,"KEY");var period=Array.IndexOf(header,"TIME_PERIOD");var value=Array.IndexOf(header,"OBS_VALUE");var freq=Array.IndexOf(header,"FREQ");var currency=Array.IndexOf(header,"CURRENCY");var denom=Array.IndexOf(header,"CURRENCY_DENOM");var isFx=expectedSeries.StartsWith("EXR.",StringComparison.Ordinal);
        if(new[]{key,period,value,freq,currency}.Any(x=>x<0)||isFx&&denom<0)throw new InvalidDataException("ECB CSV schema is missing required columns.");
        var hash="sha256:"+Convert.ToHexString(SHA256.HashData(csv)).ToLowerInvariant();var result=new List<MacroObservation>();
        foreach(var indexed in lines.Skip(1).Select((line,index)=>(line,index)))
        {
            var cells=Csv(indexed.line);var identity=cells.Length==header.Length&&cells[key]==expectedSeries;var date=default(DateOnly);var parsed=0m;var validDate=identity&&DateOnly.TryParseExact(cells[period],"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out date);var missing=identity&&string.IsNullOrWhiteSpace(cells[value]);var validValue=missing||identity&&decimal.TryParse(cells[value],NumberStyles.Float,CultureInfo.InvariantCulture,out parsed);
            if(!identity||!validDate||!validValue)throw new InvalidDataException($"ECB observation row {indexed.index+2} failed columns={cells.Length==header.Length}, identity={identity}, date={validDate}, value={validValue}.");
            result.Add(new(expectedSeries,date,missing?null:parsed,acquired,acquired,DateOnly.FromDateTime(acquired.UtcDateTime),new(9999,12,31),hash,MacroEvidenceClass.RevisedHistoryExploratory,"ECB",MacroRegion.EuroArea,isFx?$"{cells[currency]} per {cells[denom]}":definition.Units,cells[freq]=="D"?"Daily":cells[freq],isFx?cells[denom]:null,isFx?cells[currency]:null));
        }
        return result;
    }
    private static string[] Csv(string line){var cells=new List<string>();var value=new StringBuilder();var quoted=false;for(var i=0;i<line.Length;i++){var ch=line[i];if(ch=='\"'){if(quoted&&i+1<line.Length&&line[i+1]=='\"'){value.Append('\"');i++;}else quoted=!quoted;}else if(ch==','&&!quoted){cells.Add(value.ToString());value.Clear();}else value.Append(ch);}if(quoted)throw new InvalidDataException("Unterminated ECB CSV quote.");cells.Add(value.ToString());return cells.ToArray();}
    private static string HashFiles(IEnumerable<string> paths){using var hash=IncrementalHash.CreateHash(HashAlgorithmName.SHA256);foreach(var path in paths.Order(StringComparer.Ordinal)){var bytes=File.ReadAllBytes(path);hash.AppendData(bytes);}return "sha256:"+Convert.ToHexString(hash.GetHashAndReset()).ToLowerInvariant();}
    internal FinanceMacroSnapshot Snapshot()
    {
        using var c=new SqliteConnection(_connection);c.Open();var rows=new List<MacroObservation>();
        var revision=Scalar(c,"SELECT revision_id FROM macro_revisions ORDER BY created_utc DESC LIMIT 1");
        if(revision is not null)using(var x=c.CreateCommand()){x.CommandText="SELECT series_id,reference_period,value,knowledge_time_utc,acquired_utc,realtime_start,realtime_end,artifact_hash,evidence_class FROM macro_observations WHERE revision_id=$revision ORDER BY series_id,reference_period,knowledge_time_utc";x.Parameters.AddWithValue("$revision",revision);using var r=x.ExecuteReader();while(r.Read())rows.Add(new MacroObservation(r.GetString(0),DateOnly.Parse(r.GetString(1),CultureInfo.InvariantCulture),r.IsDBNull(2)?null:decimal.Parse(r.GetString(2),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(3),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(4),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(5),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(6),CultureInfo.InvariantCulture),r.GetString(7),Enum.Parse<MacroEvidenceClass>(r.GetString(8))));}
        var status=new FinanceMacroStatus("RESEARCH","FRED",rows.Count==0?"BOOTSTRAPPING":"AVAILABLE",rows.Count==0?"UNAVAILABLE":rows[0].EvidenceClass.ToString(),FredMacroPackV1.FeatureRevision,FredMacroPackV1.RegimePolicy,FredMacroPackV1.Series.Count,rows.Count,Convert.ToInt32(Scalar(c,"SELECT CAST(COUNT(*) AS TEXT) FROM macro_revisions")??"0",CultureInfo.InvariantCulture),"Public domain: citation requested; series-specific rights checked","Normalized observations and provenance retained; revalidate terms before redistribution",revision,_fred.Enabled,_fred.ApiKeyConfigured);MarketRegime? regime=null;if(rows.Count>0&&revision is not null){var cutoff=rows.Max(x=>x.KnowledgeTimeUtc);var session=rows.Max(x=>x.ReferencePeriod);regime=MacroFeatureEngine.Regime(session,cutoff,MacroFeatureEngine.At(session,cutoff,rows,revision,rows[0].EvidenceClass),revision,rows[0].EvidenceClass);}return new(status,FredMacroPackV1.Series,rows.TakeLast(100).ToArray(),regime);
    }
    internal IReadOnlyList<MacroObservation> AsOf(MacroRegion region,DateTimeOffset asOfUtc,MacroEvidenceClass evidenceClass)
    {
        if(asOfUtc.Offset!=TimeSpan.Zero)throw new ArgumentException("As-of time must be UTC.",nameof(asOfUtc));using var c=new SqliteConnection(_connection);c.Open();using var x=c.CreateCommand();x.CommandText="SELECT series_id,reference_period,value,knowledge_time_utc,acquired_utc,realtime_start,realtime_end,artifact_hash,evidence_class,provider,region,unit,frequency,base_currency,quote_currency FROM macro_observations WHERE region=$region AND evidence_class=$class AND knowledge_time_utc<=$asof ORDER BY provider,series_id,reference_period,knowledge_time_utc";x.Parameters.AddWithValue("$region",region.ToString());x.Parameters.AddWithValue("$class",evidenceClass.ToString());x.Parameters.AddWithValue("$asof",asOfUtc.ToString("O",CultureInfo.InvariantCulture));using var r=x.ExecuteReader();var rows=new List<MacroObservation>();while(r.Read())rows.Add(new(r.GetString(0),DateOnly.Parse(r.GetString(1),CultureInfo.InvariantCulture),r.IsDBNull(2)?null:decimal.Parse(r.GetString(2),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(3),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(4),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(5),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(6),CultureInfo.InvariantCulture),r.GetString(7),Enum.Parse<MacroEvidenceClass>(r.GetString(8)),r.GetString(9),Enum.Parse<MacroRegion>(r.GetString(10)),r.GetString(11),r.GetString(12),r.IsDBNull(13)?null:r.GetString(13),r.IsDBNull(14)?null:r.GetString(14)));return MacroAsOf.Select(rows,region,asOfUtc,evidenceClass);
    }
    internal FinanceRegimeAnalysis Analyze(EodhdMarketMemory market)
    {
        var snapshot=Snapshot();if(snapshot.Status.LatestRevision is null)return new("RESEARCH","UNAVAILABLE",[],"Macro Memory is bootstrapping.");using var c=new SqliteConnection(_connection);c.Open();var all=new List<MacroObservation>();using(var x=c.CreateCommand()){x.CommandText="SELECT series_id,reference_period,value,knowledge_time_utc,acquired_utc,realtime_start,realtime_end,artifact_hash,evidence_class FROM macro_observations WHERE revision_id=$revision";x.Parameters.AddWithValue("$revision",snapshot.Status.LatestRevision);using var r=x.ExecuteReader();while(r.Read())all.Add(new(r.GetString(0),DateOnly.Parse(r.GetString(1),CultureInfo.InvariantCulture),r.IsDBNull(2)?null:decimal.Parse(r.GetString(2),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(3),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(4),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(5),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(6),CultureInfo.InvariantCulture),r.GetString(7),Enum.Parse<MacroEvidenceClass>(r.GetString(8))));}
        if(all.Count==0)return new("RESEARCH","UNAVAILABLE",[],"Selected macro revision contains no observations.");var evidenceClass=all[0].EvidenceClass;var cutoff=all.Max(x=>x.KnowledgeTimeUtc);var runs=new List<RegimeAnalysisRun>();foreach(var summary in market.BacktestCatalog().Runs){var result=market.BacktestResult(summary.RunId);if(result is null||result.EquityCurve.Count<2)continue;var points=result.EquityCurve.Zip(result.EquityCurve.Skip(1),(a,b)=>(a,b,ret:a.TotalEquity==0?0:b.TotalEquity/a.TotalEquity-1)).Select(x=>(x.b.Session,x.ret,regime:MacroFeatureEngine.Regime(x.b.Session,cutoff,MacroFeatureEngine.At(x.b.Session,cutoff,all,snapshot.Status.LatestRevision,evidenceClass),snapshot.Status.LatestRevision,evidenceClass))).GroupBy(x=>x.regime.Composite).Select(g=>{decimal cumulative=0,peak=1,maxDrawdown=0;foreach(var p in g.OrderBy(x=>x.Session)){cumulative=(1+cumulative)*(1+p.ret)-1;peak=Math.Max(peak,1+cumulative);maxDrawdown=Math.Min(maxDrawdown,(1+cumulative)/peak-1);}return new RegimeAnalysisBucket(g.Key,g.Count(),cumulative,maxDrawdown,g.Count()<20?"INSUFFICIENT_SAMPLE":"Observed result; no significance claim.");}).OrderBy(x=>x.Composite,StringComparer.Ordinal).ToArray();runs.Add(new(summary.RunId,summary.StrategyId,summary.StrategyVersion,snapshot.Status.LatestRevision,FredMacroPackV1.FeatureRevision,FredMacroPackV1.RegimePolicy,evidenceClass.ToString(),points));}return new("RESEARCH",evidenceClass.ToString(),runs,evidenceClass==MacroEvidenceClass.PointInTimeCausal?"Point-in-time evidence selected explicitly; regime grouping does not change strategy logic.":"Regime grouping analyzes existing runs; it does not change strategy logic. Revised-history evidence is not point-in-time causal.");
    }
    private static void Validate(MacroObservation[] rows){if(rows.Length==0)throw new InvalidDataException("Macro candidate is empty.");var allowed=FredMacroPackV1.Series.Concat(EuropeanMacroPackV1.Riksbank).Concat(EuropeanMacroPackV1.Ecb).Select(x=>x.SeriesId).ToHashSet();if(rows.Any(x=>!allowed.Contains(x.SeriesId)||x.KnowledgeTimeUtc.Offset!=TimeSpan.Zero||x.AcquiredAtUtc.Offset!=TimeSpan.Zero||x.KnowledgeTimeUtc>x.AcquiredAtUtc||x.Value is decimal v&&(v<-10000||v>100000)||x.BaseCurrency is not null&&x.Value is decimal fx&&(fx<=0||fx>=10000)))throw new InvalidDataException("Macro candidate failed identity, time or numeric validation.");if(rows.GroupBy(x=>(x.Provider,x.SeriesId,x.ReferencePeriod,x.KnowledgeTimeUtc)).Any(x=>x.Count()>1))throw new InvalidDataException("Macro candidate contains duplicate knowledge-time observations.");}
    private static void Exec(SqliteConnection c,SqliteTransaction t,string sql,params(string,object)[] args){using var x=c.CreateCommand();x.Transaction=t;x.CommandText=sql;foreach(var a in args)x.Parameters.AddWithValue(a.Item1,a.Item2);x.ExecuteNonQuery();}
    private static string? Scalar(SqliteConnection c,string sql){using var x=c.CreateCommand();x.CommandText=sql;return x.ExecuteScalar() as string;}
}

internal static class FinanceMacroMaintenanceCommand
{
    internal static bool TryRun(string[] args,IConfiguration configuration)
    {
        if(args.Length==0||args[0] is not ("finance-macro-promote" or "finance-fred-vintage-drill" or "finance-european-macro-drill"))return false;
        if(args[0]=="finance-european-macro-drill")
        {
            if(args.Length!=3)throw new ArgumentException("Use finance-european-macro-drill <from> <to>.");var from=DateOnly.ParseExact(args[1],"yyyy-MM-dd",CultureInfo.InvariantCulture);var to=DateOnly.ParseExact(args[2],"yyyy-MM-dd",CultureInfo.InvariantCulture);var marketOptions=configuration.GetSection(EodhdFinanceOptions.Section).Get<EodhdFinanceOptions>()??new();var fredOptions=configuration.GetSection(FinanceFredOptions.Section).Get<FinanceFredOptions>()??new();var euroMemory=new FinanceMacroMemory(marketOptions,fredOptions);var euroRevisions=new List<object>();foreach(var series in EuropeanMacroPackV1.Riksbank.Select(x=>x.SeriesId)){var artifact=new RiksbankMacroProvider().AcquireAsync(series,from,to,CancellationToken.None).GetAwaiter().GetResult();var euroRevision=euroMemory.StageAndPromoteRiksbank(series,artifact.Content,artifact.AcquiredAtUtc);euroRevisions.Add(new{artifact.Provider,artifact.SeriesId,revision=euroRevision,observations=euroMemory.AsOf(MacroRegion.Sweden,artifact.AcquiredAtUtc,MacroEvidenceClass.RevisedHistoryExploratory).Count});}foreach(var series in EuropeanMacroPackV1.Ecb.Select(x=>x.SeriesId)){var artifact=new EcbMacroProvider().AcquireAsync(series,from,to,CancellationToken.None).GetAwaiter().GetResult();var euroRevision=euroMemory.StageAndPromoteEcb(series,artifact.Content,artifact.AcquiredAtUtc);euroRevisions.Add(new{artifact.Provider,artifact.SeriesId,revision=euroRevision,observations=euroMemory.AsOf(MacroRegion.EuroArea,artifact.AcquiredAtUtc,MacroEvidenceClass.RevisedHistoryExploratory).Count});}Console.WriteLine(JsonSerializer.Serialize(new{mode="RESEARCH",classification="REVISED_HISTORY_EXPLORATORY",from,to,revisions=euroRevisions}));return true;
        }
        if(args[0]=="finance-fred-vintage-drill")
        {
            if(args.Length!=6)throw new ArgumentException("Use finance-fred-vintage-drill <CPIAUCSL|UNRATE> <observation-from> <observation-to> <realtime-start> <realtime-end>.");var marketOptions=configuration.GetSection(EodhdFinanceOptions.Section).Get<EodhdFinanceOptions>()??new();var fredOptions=configuration.GetSection(FinanceFredOptions.Section).Get<FinanceFredOptions>()??new();var series=args[1].ToUpperInvariant();var from=DateOnly.ParseExact(args[2],"yyyy-MM-dd",CultureInfo.InvariantCulture);var to=DateOnly.ParseExact(args[3],"yyyy-MM-dd",CultureInfo.InvariantCulture);var realtimeStart=DateOnly.ParseExact(args[4],"yyyy-MM-dd",CultureInfo.InvariantCulture);var realtimeEnd=DateOnly.ParseExact(args[5],"yyyy-MM-dd",CultureInfo.InvariantCulture);var bytes=new FredApiClient(fredOptions).GetVintageObservationsAsync(series,from,to,realtimeStart,realtimeEnd,CancellationToken.None).GetAwaiter().GetResult();var vintageMemory=new FinanceMacroMemory(marketOptions);var vintageRevision=vintageMemory.StageAndPromoteVintage(series,bytes,fredOptions,DateTimeOffset.UtcNow);Console.WriteLine(JsonSerializer.Serialize(new{revision=vintageRevision,series,classification="POINT_IN_TIME_CAUSAL",fredApiKeyConfigured=fredOptions.ApiKeyConfigured}));return true;
        }
        if(args.Length!=6)throw new ArgumentException("Use finance-macro-promote <DFF.csv> <DGS2.csv> <DGS10.csv> <CPIAUCSL.csv> <UNRATE.csv>.");
        var market=configuration.GetSection(EodhdFinanceOptions.Section).Get<EodhdFinanceOptions>()??new();var fred=configuration.GetSection(FinanceFredOptions.Section).Get<FinanceFredOptions>()??new();var memory=new FinanceMacroMemory(market);var revision=memory.StageAndPromoteCsvPack(args.Skip(1).ToArray(),fred);var snapshot=memory.Snapshot();Console.WriteLine(JsonSerializer.Serialize(new{revision,series=5,observations=snapshot.Status.ObservationCount,classification="REVISED_HISTORY_EXPLORATORY",fredApiKeyConfigured=fred.ApiKeyConfigured,regime=snapshot.LatestRegime}));return true;
    }
}
