using System.Globalization;
using BigBrain.Modules.Finance;
using Microsoft.Data.Sqlite;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

#pragma warning disable CS8602 // Candidate file identity is validated immediately after extraction.
#pragma warning disable CA1859 // Interface return types document bounded pipeline contracts.

namespace BigBrain.Api.Finance;

public sealed record FinanceFredOptions
{
    public const string Section="Finance:Fred";
    public bool Enabled { get; set; }
    public string ApiKey { get; set; }="";
    public string BaseUrl { get; set; }="https://api.stlouisfed.org";
    public int TimeoutSeconds { get; set; }=30;
    public int MaximumVintageObservations { get; set; }=5000;
    public string QuarantineDirectory { get; set; }=Path.Combine(Path.GetTempPath(),"bigbrain-finance","macro-quarantine");
    internal bool ApiKeyConfigured=>!string.IsNullOrWhiteSpace(ApiKey);
    internal void Validate(){if(!Uri.TryCreate(BaseUrl,UriKind.Absolute,out var uri)||uri.Scheme!=Uri.UriSchemeHttps||!string.Equals(uri.Host,"api.stlouisfed.org",StringComparison.OrdinalIgnoreCase)||TimeoutSeconds is <5 or >120||MaximumVintageObservations is <1 or >10000)throw new InvalidOperationException("FRED configuration is invalid or not first-party bounded.");}
}

internal sealed record FinanceMacroStatus(string OperatingMode,string Provider,string Availability,string EvidenceClass,string FeatureRevision,string RegimePolicy,int SeriesCount,int ObservationCount,int RevisionCount,string Rights,string Retention,string? LatestRevision,bool FredEnabled,bool FredApiKeyConfigured);
internal sealed record FinanceMacroSnapshot(FinanceMacroStatus Status,IReadOnlyList<MacroSeriesDefinition> Series,IReadOnlyList<MacroObservation> Observations,MarketRegime? LatestRegime);
internal sealed record RegimeAnalysisBucket(string Composite,int Sessions,decimal Return,decimal MaximumDrawdown,string EvidenceWarning);
internal sealed record RegimeAnalysisRun(string RunId,string StrategyId,string StrategyVersion,string MacroRevision,string FeatureRevision,string RegimePolicy,string EvidenceClass,IReadOnlyList<RegimeAnalysisBucket> Regimes);
internal sealed record FinanceRegimeAnalysis(string OperatingMode,string Classification,IReadOnlyList<RegimeAnalysisRun> Runs,string Limitation);

internal sealed class FinanceMacroMemory
{
    private readonly string _connection;
    private readonly FinanceFredOptions _fred;
    internal FinanceMacroMemory(EodhdFinanceOptions options,FinanceFredOptions? fred=null){FinanceSchemaMigrator.Migrate(options.DatabasePath);_connection=new SqliteConnectionStringBuilder{DataSource=options.DatabasePath}.ToString();_fred=fred??new();}
    internal string StageAndPromoteCsvPack(IReadOnlyList<string> paths,FinanceFredOptions options)
    {
        options.Validate();if(paths.Count==0)throw new InvalidDataException("Macro candidate is empty.");Directory.CreateDirectory(options.QuarantineDirectory);var acquired=new DateTimeOffset(DateOnly.FromDateTime(DateTime.UtcNow).ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);var expected=paths.Select(Path.GetFileNameWithoutExtension).Select(x=>x?.ToUpperInvariant()??"").Order(StringComparer.Ordinal).ToArray();var artifactHash=HashFiles(paths);var candidateId="fred-candidate-"+artifactHash[7..23];var root=Path.Combine(options.QuarantineDirectory,candidateId);Directory.CreateDirectory(root);var staged=new List<string>();foreach(var source in paths.Order(StringComparer.Ordinal)){var target=Path.Combine(root,Path.GetFileName(source));File.Copy(source,target,true);staged.Add(target);}try{if(expected.Distinct(StringComparer.Ordinal).Count()!=expected.Length||expected.Any(x=>!FredMacroPackV1.Series.Any(s=>s.SeriesId==x)))throw new InvalidDataException("Macro candidate contains an unexpected or duplicate series.");var rows=ParseFredCsv(staged,acquired,MacroEvidenceClass.RevisedHistoryExploratory);return RecordCandidateAndPromote(candidateId,"https://fred.stlouisfed.org/graph/fredgraph.csv","PublicDomainCitationRequested","https://fred.stlouisfed.org/legal/terms/",staged,artifactHash,rows,"fred-csv-v1");}catch(Exception ex) when(ex is InvalidDataException or FormatException or JsonException){RecordRejectedCandidate(candidateId,"https://fred.stlouisfed.org/graph/fredgraph.csv",staged,artifactHash,acquired,expected,ex.Message);throw;}
    }
    internal string StageAndPromoteVintage(string seriesId,byte[] json,FinanceFredOptions options,DateTimeOffset acquired)
    {
        options.Validate();if(seriesId is not ("CPIAUCSL" or "UNRATE"))throw new InvalidDataException("Vintage drill is bounded to CPIAUCSL or UNRATE.");var hash="sha256:"+Convert.ToHexString(SHA256.HashData(json)).ToLowerInvariant();var id="fred-vintage-candidate-"+hash[7..23];var root=Path.Combine(options.QuarantineDirectory,id);Directory.CreateDirectory(root);var path=Path.Combine(root,$"{seriesId}.json");File.WriteAllBytes(path,json);try{var rows=ParseVintageJson(seriesId,json,acquired,options.MaximumVintageObservations);return RecordCandidateAndPromote(id,"https://api.stlouisfed.org/fred/series/observations","PublicDomainCitationRequested","https://fred.stlouisfed.org/docs/api/terms_of_use.html",[path],hash,rows,"fred-api-vintage-json-v2");}catch(Exception ex) when(ex is InvalidDataException or FormatException or JsonException or KeyNotFoundException or InvalidOperationException){RecordRejectedCandidate(id,"https://api.stlouisfed.org/fred/series/observations",[path],hash,acquired,[seriesId],ex.Message);throw;}
    }
    private string Promote(IEnumerable<MacroObservation> input)
    {
        var rows=input.OrderBy(x=>x.SeriesId).ThenBy(x=>x.ReferencePeriod).ThenBy(x=>x.KnowledgeTimeUtc).ToArray();Validate(rows);var hash=MacroFeatureEngine.Hash(rows);var id="fred-"+hash[7..23];using var c=new SqliteConnection(_connection);c.Open();using var t=c.BeginTransaction();Exec(c,t,"INSERT OR IGNORE INTO macro_revisions VALUES($id,'FRED',$hash,$at,$class,'PASS')",("$id",id),("$hash",hash),("$at",DateTimeOffset.UtcNow.ToString("O",CultureInfo.InvariantCulture)),("$class",rows[0].EvidenceClass.ToString()));
        foreach(var r in rows)Exec(c,t,"INSERT OR IGNORE INTO macro_observations VALUES($revision,$series,$period,$value,$knowledge,$acquired,$start,$end,$hash,$class)",("$revision",id),("$series",r.SeriesId),("$period",r.ReferencePeriod.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$value",r.Value is null?(object)DBNull.Value:r.Value.Value.ToString(CultureInfo.InvariantCulture)),("$knowledge",r.KnowledgeTimeUtc.ToString("O",CultureInfo.InvariantCulture)),("$acquired",r.AcquiredAtUtc.ToString("O",CultureInfo.InvariantCulture)),("$start",r.RealtimeStart.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$end",r.RealtimeEnd.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),("$hash",r.ArtifactHash),("$class",r.EvidenceClass.ToString()));t.Commit();return id;
    }
    private string RecordCandidateAndPromote(string candidateId,string sourceUrl,string rights,string rightsUrl,IReadOnlyList<string> staged,string artifactHash,IReadOnlyList<MacroObservation> rows,string schema)
    {
        Validate(rows.ToArray());var schemaHash="sha256:"+Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(schema+"|"+string.Join('|',rows.Select(x=>x.SeriesId).Distinct().Order())))).ToLowerInvariant();using var c=new SqliteConnection(_connection);c.Open();using(var x=c.CreateCommand()){x.CommandText="INSERT OR IGNORE INTO macro_candidates VALUES($id,'FRED',$url,$path,$hash,$at,$rights,$rightsUrl,$series,$schema,'PASS','APPROVED',NULL)";x.Parameters.AddWithValue("$id",candidateId);x.Parameters.AddWithValue("$url",sourceUrl);x.Parameters.AddWithValue("$path",JsonSerializer.Serialize(staged.Select(Path.GetFileName)));x.Parameters.AddWithValue("$hash",artifactHash);x.Parameters.AddWithValue("$at",rows.Max(r=>r.AcquiredAtUtc).ToString("O",CultureInfo.InvariantCulture));x.Parameters.AddWithValue("$rights",rights);x.Parameters.AddWithValue("$rightsUrl",rightsUrl);x.Parameters.AddWithValue("$series",JsonSerializer.Serialize(rows.Select(r=>r.SeriesId).Distinct().Order()));x.Parameters.AddWithValue("$schema",schemaHash);x.ExecuteNonQuery();}var revision=Promote(rows);using(var x=c.CreateCommand()){x.CommandText="UPDATE macro_candidates SET promotion_decision='PROMOTED',canonical_revision_id=$revision WHERE candidate_id=$id AND validation_result='PASS'";x.Parameters.AddWithValue("$revision",revision);x.Parameters.AddWithValue("$id",candidateId);x.ExecuteNonQuery();}return revision;
    }
    private void RecordRejectedCandidate(string candidateId,string sourceUrl,IReadOnlyList<string> staged,string artifactHash,DateTimeOffset acquired,IReadOnlyList<string> series,string reason)
    {
        using var c=new SqliteConnection(_connection);c.Open();using var x=c.CreateCommand();x.CommandText="INSERT OR REPLACE INTO macro_candidates VALUES($id,'FRED',$url,$path,$hash,$at,'PublicDomainCitationRequested','https://fred.stlouisfed.org/docs/api/terms_of_use.html',$series,'UNVERIFIED','FAIL','REJECTED',NULL)";x.Parameters.AddWithValue("$id",candidateId);x.Parameters.AddWithValue("$url",sourceUrl);x.Parameters.AddWithValue("$path",JsonSerializer.Serialize(staged.Select(Path.GetFileName)));x.Parameters.AddWithValue("$hash",artifactHash);x.Parameters.AddWithValue("$at",acquired.ToString("O",CultureInfo.InvariantCulture));x.Parameters.AddWithValue("$series",JsonSerializer.Serialize(series));x.ExecuteNonQuery();_ = reason;
    }
    private static IReadOnlyList<MacroObservation> ParseFredCsv(IReadOnlyList<string> paths,DateTimeOffset acquired,MacroEvidenceClass evidence){var rows=new List<MacroObservation>();foreach(var path in paths){var id=Path.GetFileNameWithoutExtension(path).ToUpperInvariant();var bytes=File.ReadAllBytes(path);var hash="sha256:"+Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();using var reader=new StringReader(Encoding.UTF8.GetString(bytes));var header=reader.ReadLine()?.Trim();if(header!=$"observation_date,{id}"&&header!=$"DATE,{id}")throw new InvalidDataException($"Unexpected FRED CSV schema for {id}.");string? line;while((line=reader.ReadLine()) is not null){var parts=line.Split(',');if(parts.Length!=2||!DateOnly.TryParseExact(parts[0],"yyyy-MM-dd",CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.None,out var period))throw new InvalidDataException($"Malformed FRED row for {id}.");decimal? value=string.IsNullOrWhiteSpace(parts[1])||parts[1]=="."?null:decimal.TryParse(parts[1],System.Globalization.NumberStyles.Float,CultureInfo.InvariantCulture,out var parsed)?parsed:throw new InvalidDataException($"Malformed FRED value for {id}.");rows.Add(new(id,period,value,acquired,acquired,new(2026,8,16),new(9999,12,31),hash,evidence));}}return rows;}
    private static IReadOnlyList<MacroObservation> ParseVintageJson(string seriesId,byte[] json,DateTimeOffset acquired,int maximum)
    {
        using var doc=JsonDocument.Parse(json);var root=doc.RootElement;if(root.GetProperty("output_type").GetInt32()!=2)throw new InvalidDataException("FRED vintage response must use output_type=2.");var realtimeEnd=DateOnly.ParseExact(root.GetProperty("realtime_end").GetString()!,"yyyy-MM-dd",CultureInfo.InvariantCulture);var observations=root.GetProperty("observations");if(observations.ValueKind!=JsonValueKind.Array)throw new InvalidDataException("FRED vintage response observations must be an array.");var columns=observations.EnumerateArray().SelectMany(x=>x.EnumerateObject()).Where(x=>x.Name!="date").Select(x=>x.Name).Distinct(StringComparer.Ordinal).Select(name=>{var prefix=seriesId+"_";if(!name.StartsWith(prefix,StringComparison.Ordinal)||!DateOnly.TryParseExact(name[prefix.Length..],"yyyyMMdd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var vintage))throw new InvalidDataException("FRED vintage response contains an unexpected series/vintage column.");return(name,vintage);}).OrderBy(x=>x.vintage).ToArray();if(columns.Length==0)throw new InvalidDataException("FRED vintage response contains no vintage columns.");var hash="sha256:"+Convert.ToHexString(SHA256.HashData(json)).ToLowerInvariant();var result=new List<MacroObservation>();foreach(var item in observations.EnumerateArray()){var reference=DateOnly.ParseExact(item.GetProperty("date").GetString()!,"yyyy-MM-dd",CultureInfo.InvariantCulture);for(var i=0;i<columns.Length;i++){var column=columns[i];if(!item.TryGetProperty(column.name,out var valueElement))continue;if(result.Count>=maximum)throw new InvalidDataException("FRED vintage response exceeds bounded observation limit.");var text=valueElement.GetString()??throw new InvalidDataException("FRED vintage value must be a string.");decimal? value=text=="."?null:decimal.TryParse(text,NumberStyles.Float,CultureInfo.InvariantCulture,out var parsed)?parsed:throw new InvalidDataException("FRED vintage value is malformed.");var end=i+1<columns.Length?columns[i+1].vintage.AddDays(-1):realtimeEnd;if(end<column.vintage)throw new InvalidDataException("FRED vintage periods are not monotonic.");var knowledge=new DateTimeOffset(column.vintage.AddDays(1).ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);result.Add(new(seriesId,reference,value,knowledge,acquired,column.vintage,end,hash,MacroEvidenceClass.PointInTimeCausal));}}return result;
    }
    private static string HashFiles(IEnumerable<string> paths){using var hash=IncrementalHash.CreateHash(HashAlgorithmName.SHA256);foreach(var path in paths.Order(StringComparer.Ordinal)){var bytes=File.ReadAllBytes(path);hash.AppendData(bytes);}return "sha256:"+Convert.ToHexString(hash.GetHashAndReset()).ToLowerInvariant();}
    internal FinanceMacroSnapshot Snapshot()
    {
        using var c=new SqliteConnection(_connection);c.Open();var rows=new List<MacroObservation>();
        var revision=Scalar(c,"SELECT revision_id FROM macro_revisions ORDER BY created_utc DESC LIMIT 1");
        if(revision is not null)using(var x=c.CreateCommand()){x.CommandText="SELECT series_id,reference_period,value,knowledge_time_utc,acquired_utc,realtime_start,realtime_end,artifact_hash,evidence_class FROM macro_observations WHERE revision_id=$revision ORDER BY series_id,reference_period,knowledge_time_utc";x.Parameters.AddWithValue("$revision",revision);using var r=x.ExecuteReader();while(r.Read())rows.Add(new MacroObservation(r.GetString(0),DateOnly.Parse(r.GetString(1),CultureInfo.InvariantCulture),r.IsDBNull(2)?null:decimal.Parse(r.GetString(2),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(3),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(4),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(5),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(6),CultureInfo.InvariantCulture),r.GetString(7),Enum.Parse<MacroEvidenceClass>(r.GetString(8))));}
        var status=new FinanceMacroStatus("RESEARCH","FRED",rows.Count==0?"BOOTSTRAPPING":"AVAILABLE",rows.Count==0?"UNAVAILABLE":rows[0].EvidenceClass.ToString(),FredMacroPackV1.FeatureRevision,FredMacroPackV1.RegimePolicy,FredMacroPackV1.Series.Count,rows.Count,Convert.ToInt32(Scalar(c,"SELECT CAST(COUNT(*) AS TEXT) FROM macro_revisions")??"0",CultureInfo.InvariantCulture),"Public domain: citation requested; series-specific rights checked","Normalized observations and provenance retained; revalidate terms before redistribution",revision,_fred.Enabled,_fred.ApiKeyConfigured);MarketRegime? regime=null;if(rows.Count>0&&revision is not null){var cutoff=rows.Max(x=>x.KnowledgeTimeUtc);var session=rows.Max(x=>x.ReferencePeriod);regime=MacroFeatureEngine.Regime(session,cutoff,MacroFeatureEngine.At(session,cutoff,rows,revision,rows[0].EvidenceClass),revision,rows[0].EvidenceClass);}return new(status,FredMacroPackV1.Series,rows.TakeLast(100).ToArray(),regime);
    }
    internal FinanceRegimeAnalysis Analyze(EodhdMarketMemory market)
    {
        var snapshot=Snapshot();if(snapshot.Status.LatestRevision is null)return new("RESEARCH","UNAVAILABLE",[],"Macro Memory is bootstrapping.");using var c=new SqliteConnection(_connection);c.Open();var all=new List<MacroObservation>();using(var x=c.CreateCommand()){x.CommandText="SELECT series_id,reference_period,value,knowledge_time_utc,acquired_utc,realtime_start,realtime_end,artifact_hash,evidence_class FROM macro_observations WHERE revision_id=$revision";x.Parameters.AddWithValue("$revision",snapshot.Status.LatestRevision);using var r=x.ExecuteReader();while(r.Read())all.Add(new(r.GetString(0),DateOnly.Parse(r.GetString(1),CultureInfo.InvariantCulture),r.IsDBNull(2)?null:decimal.Parse(r.GetString(2),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(3),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(4),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(5),CultureInfo.InvariantCulture),DateOnly.Parse(r.GetString(6),CultureInfo.InvariantCulture),r.GetString(7),Enum.Parse<MacroEvidenceClass>(r.GetString(8))));}
        if(all.Count==0)return new("RESEARCH","UNAVAILABLE",[],"Selected macro revision contains no observations.");var evidenceClass=all[0].EvidenceClass;var cutoff=all.Max(x=>x.KnowledgeTimeUtc);var runs=new List<RegimeAnalysisRun>();foreach(var summary in market.BacktestCatalog().Runs){var result=market.BacktestResult(summary.RunId);if(result is null||result.EquityCurve.Count<2)continue;var points=result.EquityCurve.Zip(result.EquityCurve.Skip(1),(a,b)=>(a,b,ret:a.TotalEquity==0?0:b.TotalEquity/a.TotalEquity-1)).Select(x=>(x.b.Session,x.ret,regime:MacroFeatureEngine.Regime(x.b.Session,cutoff,MacroFeatureEngine.At(x.b.Session,cutoff,all,snapshot.Status.LatestRevision,evidenceClass),snapshot.Status.LatestRevision,evidenceClass))).GroupBy(x=>x.regime.Composite).Select(g=>{decimal cumulative=0,peak=1,maxDrawdown=0;foreach(var p in g.OrderBy(x=>x.Session)){cumulative=(1+cumulative)*(1+p.ret)-1;peak=Math.Max(peak,1+cumulative);maxDrawdown=Math.Min(maxDrawdown,(1+cumulative)/peak-1);}return new RegimeAnalysisBucket(g.Key,g.Count(),cumulative,maxDrawdown,g.Count()<20?"INSUFFICIENT_SAMPLE":"Observed result; no significance claim.");}).OrderBy(x=>x.Composite,StringComparer.Ordinal).ToArray();runs.Add(new(summary.RunId,summary.StrategyId,summary.StrategyVersion,snapshot.Status.LatestRevision,FredMacroPackV1.FeatureRevision,FredMacroPackV1.RegimePolicy,evidenceClass.ToString(),points));}return new("RESEARCH",evidenceClass.ToString(),runs,evidenceClass==MacroEvidenceClass.PointInTimeCausal?"Point-in-time evidence selected explicitly; regime grouping does not change strategy logic.":"Regime grouping analyzes existing runs; it does not change strategy logic. Revised-history evidence is not point-in-time causal.");
    }
    private static void Validate(MacroObservation[] rows){if(rows.Length==0)throw new InvalidDataException("Macro candidate is empty.");var allowed=FredMacroPackV1.Series.Select(x=>x.SeriesId).ToHashSet();if(rows.Any(x=>!allowed.Contains(x.SeriesId)||x.KnowledgeTimeUtc.Offset!=TimeSpan.Zero||x.AcquiredAtUtc.Offset!=TimeSpan.Zero||x.KnowledgeTimeUtc>x.AcquiredAtUtc||x.Value is decimal v&&(v<-10000||v>100000)))throw new InvalidDataException("Macro candidate failed identity, time or numeric validation.");if(rows.GroupBy(x=>(x.SeriesId,x.ReferencePeriod,x.KnowledgeTimeUtc)).Any(x=>x.Count()>1))throw new InvalidDataException("Macro candidate contains duplicate knowledge-time observations.");}
    private static void Exec(SqliteConnection c,SqliteTransaction t,string sql,params(string,object)[] args){using var x=c.CreateCommand();x.Transaction=t;x.CommandText=sql;foreach(var a in args)x.Parameters.AddWithValue(a.Item1,a.Item2);x.ExecuteNonQuery();}
    private static string? Scalar(SqliteConnection c,string sql){using var x=c.CreateCommand();x.CommandText=sql;return x.ExecuteScalar() as string;}
}

internal static class FinanceMacroMaintenanceCommand
{
    internal static bool TryRun(string[] args,IConfiguration configuration)
    {
        if(args.Length==0||args[0] is not ("finance-macro-promote" or "finance-fred-vintage-drill"))return false;
        if(args[0]=="finance-fred-vintage-drill")
        {
            if(args.Length!=6)throw new ArgumentException("Use finance-fred-vintage-drill <CPIAUCSL|UNRATE> <observation-from> <observation-to> <realtime-start> <realtime-end>.");var marketOptions=configuration.GetSection(EodhdFinanceOptions.Section).Get<EodhdFinanceOptions>()??new();var fredOptions=configuration.GetSection(FinanceFredOptions.Section).Get<FinanceFredOptions>()??new();var series=args[1].ToUpperInvariant();var from=DateOnly.ParseExact(args[2],"yyyy-MM-dd",CultureInfo.InvariantCulture);var to=DateOnly.ParseExact(args[3],"yyyy-MM-dd",CultureInfo.InvariantCulture);var realtimeStart=DateOnly.ParseExact(args[4],"yyyy-MM-dd",CultureInfo.InvariantCulture);var realtimeEnd=DateOnly.ParseExact(args[5],"yyyy-MM-dd",CultureInfo.InvariantCulture);var bytes=new FredApiClient(fredOptions).GetVintageObservationsAsync(series,from,to,realtimeStart,realtimeEnd,CancellationToken.None).GetAwaiter().GetResult();var vintageMemory=new FinanceMacroMemory(marketOptions);var vintageRevision=vintageMemory.StageAndPromoteVintage(series,bytes,fredOptions,DateTimeOffset.UtcNow);Console.WriteLine(JsonSerializer.Serialize(new{revision=vintageRevision,series,classification="POINT_IN_TIME_CAUSAL",fredApiKeyConfigured=fredOptions.ApiKeyConfigured}));return true;
        }
        if(args.Length!=6)throw new ArgumentException("Use finance-macro-promote <DFF.csv> <DGS2.csv> <DGS10.csv> <CPIAUCSL.csv> <UNRATE.csv>.");
        var market=configuration.GetSection(EodhdFinanceOptions.Section).Get<EodhdFinanceOptions>()??new();var fred=configuration.GetSection(FinanceFredOptions.Section).Get<FinanceFredOptions>()??new();var memory=new FinanceMacroMemory(market);var revision=memory.StageAndPromoteCsvPack(args.Skip(1).ToArray(),fred);var snapshot=memory.Snapshot();Console.WriteLine(JsonSerializer.Serialize(new{revision,series=5,observations=snapshot.Status.ObservationCount,classification="REVISED_HISTORY_EXPLORATORY",fredApiKeyConfigured=fred.ApiKeyConfigured,regime=snapshot.LatestRegime}));return true;
    }
}
