import { useEffect,useLayoutEffect,useRef,useState } from 'react'
import { createPortal } from 'react-dom'
import type { ShoppingItem } from './types'
export function ShoppingItemRow({item,menuOpen,onMenuOpen,onMenuClose,onToggle,onEdit,onDelete}:{item:ShoppingItem;menuOpen:boolean;onMenuOpen:()=>void;onMenuClose:()=>void;onToggle:()=>void;onEdit:(name:string,quantity:number)=>void;onDelete:()=>void}){
 const [editing,setEditing]=useState(false);const [name,setName]=useState(item.name);const [quantity,setQuantity]=useState(item.quantity);const [position,setPosition]=useState({left:12,top:12,visibility:'hidden' as 'hidden'|'visible'});const trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null),editInput=useRef<HTMLInputElement>(null)
 useLayoutEffect(()=>{if(!menuOpen)return;const triggerRect=trigger.current?.getBoundingClientRect(),menuRect=menu.current?.getBoundingClientRect();if(!triggerRect||!menuRect)return;const margin=12;const left=Math.min(Math.max(margin,triggerRect.right-menuRect.width),window.innerWidth-menuRect.width-margin);const below=triggerRect.bottom+6;const top=below+menuRect.height<=window.innerHeight-margin?below:Math.max(margin,triggerRect.top-menuRect.height-6);setPosition({left,top,visibility:'visible'})},[menuOpen])
 useLayoutEffect(()=>{if(menuOpen&&position.visibility==='visible')menu.current?.querySelector<HTMLElement>('button')?.focus({preventScroll:true})},[menuOpen,position])
 useEffect(()=>{if(!menuOpen)return;const restoreFocus=()=>trigger.current?.focus({preventScroll:true});const close=(event:PointerEvent)=>{if(!menu.current?.contains(event.target as Node)&&!trigger.current?.contains(event.target as Node)){onMenuClose();restoreFocus()}};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();onMenuClose();restoreFocus()}};const resize=()=>{onMenuClose();restoreFocus()};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key,true);window.addEventListener('resize',resize);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key,true);window.removeEventListener('resize',resize)}},[menuOpen,onMenuClose])
 useLayoutEffect(()=>{if(editing)editInput.current?.focus()},[editing])
 return <li className={`shopping-item${item.purchased?' shopping-item--purchased':''}`}>
  <label className="shopping-item__check"><input aria-label={`${item.purchased?'Återställ':'Markera som köpt'} ${item.name}`} checked={item.purchased} onChange={onToggle} type="checkbox"/><span aria-hidden="true"/></label>
  {editing?<form className="shopping-item__edit" onSubmit={e=>{e.preventDefault();onEdit(name,quantity);setEditing(false)}}><input ref={editInput} aria-label="Varans namn" maxLength={120} value={name} onChange={e=>setName(e.target.value)}/><input aria-label="Antal" min={1} max={999} type="number" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/><button type="submit">Spara</button><button type="button" onClick={()=>setEditing(false)}>Avbryt</button></form>:<><span className="shopping-item__name">{item.name}{item.quantity>1&&<strong> × {item.quantity}</strong>}<span className="sr-only">, {item.purchased?'köpt':'inte köpt'}</span></span><button ref={trigger} aria-expanded={menuOpen} aria-haspopup="menu" aria-label={`Åtgärder för ${item.name}`} className="shopping-item__menu-trigger" onClick={()=>menuOpen?onMenuClose():onMenuOpen()} type="button">•••</button>{menuOpen&&createPortal(<div ref={menu} aria-label={`Åtgärder för ${item.name}`} className="shopping-item__menu" role="menu" style={position}><button role="menuitem" type="button" onClick={()=>{onMenuClose();setEditing(true)}}>Redigera vara</button><button role="menuitem" type="button" onClick={()=>{onMenuClose();onDelete()}}>Ta bort vara från inköpslistan</button></div>,document.body)}</>}
 </li>
}
