import { useEffect,useLayoutEffect,useRef,useState } from 'react'
import { createPortal } from 'react-dom'
import { ApiError } from '../api'
import { CollapsibleModule } from '../dashboard/CollapsibleModule'
import * as api from './shoppingListApi'
import type { FrequentItem,ShoppingItem,ShoppingSnapshot,ShoppingSuggestion } from './types'
import { ShoppingItemRow } from './ShoppingItemRow'
import { ShoppingSuggestions } from './ShoppingSuggestions'

export function ShoppingList({expanded,onToggle,status}:{expanded:boolean;onToggle:()=>void;status:string}){
 const [data,setData]=useState<ShoppingSnapshot>({items:[],sessionId:null}),[frequent,setFrequent]=useState<FrequentItem[]>([]),[error,setError]=useState(false),[mode,setMode]=useState(false)
 const load=async()=>{try{setData(await api.getShoppingList());setFrequent(await api.getFrequentItems());setError(false)}catch{setError(true)}}
 useEffect(()=>{void load()},[])
 const remaining=data.items.filter(x=>!x.purchased)
 return <><CollapsibleModule className="shopping-list" moduleId="shopping-list" title="Inköpslista" expanded={expanded} onToggle={onToggle} actions={!['available','loading'].includes(status.toLowerCase())?<span className="status-badge status-badge--unavailable">{status}</span>:undefined} collapsedSummary={<div className="shopping-compact"><strong>{remaining.length} kvar</strong><QuickAdd inputId="shopping-collapsed-input" onAdded={load}/>{remaining.slice(0,3).map(x=><span key={x.id}>{x.name}{x.quantity>1?` × ${x.quantity}`:''}</span>)}{data.items.length===0&&<span>Inköpslistan är tom.</span>}<button className="secondary-button" onClick={()=>setMode(true)} type="button">Öppna inköpslistan</button></div>}>
  {error?<p className="notice notice--error" role="alert">Inköpslistan kunde inte laddas.</p>:<><QuickAdd inputId="shopping-expanded-input" onAdded={load}/><p>{remaining.length} kvar</p><button className="primary-button" onClick={()=>setMode(true)} type="button">Öppna handlingsläge</button></>}
 </CollapsibleModule>{mode&&createPortal(<ShoppingMode data={data} frequent={frequent} reload={load} onClose={()=>setMode(false)}/>,document.body)}</>
}

function QuickAdd({inputId,onAdded}:{inputId:string;onAdded:()=>Promise<void>}){const [name,setName]=useState(''),[message,setMessage]=useState(''),[focusAfterSuccess,setFocusAfterSuccess]=useState(0);const input=useRef<HTMLInputElement>(null);useLayoutEffect(()=>{if(focusAfterSuccess>0)input.current?.focus({preventScroll:true})},[focusAfterSuccess]);return <form className="shopping-quick-add" onSubmit={async e=>{e.preventDefault();try{await api.addShoppingItem(name);setName('');setMessage('Tillagd.');await onAdded();setFocusAfterSuccess(value=>value+1)}catch(error){setMessage(error instanceof Error?error.message:'Kunde inte lägga till varan.');if(error instanceof ApiError&&error.code==='shoppingListInvalidRequest')input.current?.focus({preventScroll:true})}}}><label className="sr-only" htmlFor={inputId}>Lägg till vara</label><input ref={input} id={inputId} maxLength={120} placeholder="Lägg till vara" value={name} onChange={e=>setName(e.target.value)}/><button type="submit">+ Lägg till vara</button><span aria-live="polite" className="sr-only">{message}</span></form>}

function ShoppingMode({data,frequent,reload,onClose}:{data:ShoppingSnapshot;frequent:FrequentItem[];reload:()=>Promise<void>;onClose:()=>void}){
 const [name,setName]=useState(''),[suggestions,setSuggestions]=useState<ShoppingSuggestion[]>([]),[active,setActive]=useState(-1),[notice,setNotice]=useState(''),[duplicate,setDuplicate]=useState<{name:string;item:ShoppingItem}|null>(null),[finish,setFinish]=useState(false),[purchasedOpen,setPurchasedOpen]=useState(false),[openMenuId,setOpenMenuId]=useState<string|null>(null),[focusAfterSuccess,setFocusAfterSuccess]=useState(0)
 const input=useRef<HTMLInputElement>(null),close=useRef<HTMLButtonElement>(null),duplicateAction=useRef<HTMLButtonElement>(null),returnFocus=useRef<HTMLElement|null>(document.activeElement as HTMLElement)
 useEffect(()=>{const root=document.getElementById('root');document.body.classList.add('shopping-mode-open');root?.setAttribute('inert','');input.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(document.getElementById('shopping-suggestions')){setSuggestions([]);return}onClose();return}if(e.key==='Tab'){const mode=document.querySelector<HTMLElement>('.shopping-mode');const focusable=[...(mode?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),summary,[href]')??[])].filter(x=>x.offsetParent!==null||x===document.activeElement);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.classList.remove('shopping-mode-open');root?.removeAttribute('inert');document.removeEventListener('keydown',key);returnFocus.current?.focus()}},[])
 useEffect(()=>{let current=true;if(!name.trim()){setSuggestions([]);return}const timer=setTimeout(()=>api.getShoppingSuggestions(name).then(x=>current&&setSuggestions(x)),120);return()=>{current=false;clearTimeout(timer)}},[name])
 useLayoutEffect(()=>{if(focusAfterSuccess>0)input.current?.focus({preventScroll:true})},[focusAfterSuccess])
 useLayoutEffect(()=>{if(duplicate)duplicateAction.current?.focus({preventScroll:true})},[duplicate])
 const closeDuplicate=()=>{setDuplicate(null);input.current?.focus({preventScroll:true})}
 const add=async(raw=name)=>{const normalized=raw.trim().replace(/\s+/g,' ').normalize().toLocaleUpperCase('sv-SE');const localDuplicate=data.items.find(x=>x.normalizedName===normalized);if(localDuplicate){setDuplicate({name:localDuplicate.name,item:localDuplicate});setSuggestions([]);return}try{await api.addShoppingItem(raw);setName('');setSuggestions([]);setNotice(`${raw.trim()} har lagts till.`);await reload();setFocusAfterSuccess(value=>value+1)}catch(error){if(error instanceof ApiError&&(error.code==='shoppingListDuplicate'||error.code==='shoppingListPurchasedDuplicate')){const item=data.items.find(x=>x.normalizedName===normalized);if(item)setDuplicate({name:item.name,item});else setNotice(error.message)}else{setNotice(error instanceof Error?error.message:'Varan kunde inte läggas till.');if(error instanceof ApiError&&error.code==='shoppingListInvalidRequest')input.current?.focus({preventScroll:true})}}}
 const unpurchased=data.items.filter(x=>!x.purchased),purchased=data.items.filter(x=>x.purchased)
 const row=(item:ShoppingItem)=><ShoppingItemRow key={item.id} item={item} menuOpen={openMenuId===item.id} onMenuOpen={()=>setOpenMenuId(item.id)} onMenuClose={()=>setOpenMenuId(null)} onToggle={async()=>{item.purchased?await api.restoreShoppingItem(item.id):await api.purchaseShoppingItem(item.id);await reload()}} onEdit={async(n,q)=>{try{await api.updateShoppingItem(item.id,n,q);await reload()}catch(e){setNotice(e instanceof Error?e.message:'Kunde inte redigera.')}}} onDelete={async()=>{if(window.confirm(`Ta bort ${item.name}?`)){await api.deleteShoppingItem(item.id);await reload()}}}/>
 return <div aria-labelledby="shopping-mode-title" aria-modal="true" className="shopping-mode" role="dialog"><div className="shopping-mode__app"><header><button ref={close} className="secondary-button" onClick={onClose} type="button">Tillbaka</button><div><h2 id="shopping-mode-title">Inköpslista</h2><p>{unpurchased.length} kvar</p></div></header><form className="shopping-add" onSubmit={e=>{e.preventDefault();void add()}}><label htmlFor="shopping-mode-input">Lägg till vara</label><div><input ref={input} id="shopping-mode-input" role="combobox" aria-autocomplete="list" aria-controls="shopping-suggestions" aria-expanded={suggestions.length>0} aria-activedescendant={active>=0?`shopping-suggestion-${active}`:undefined} maxLength={120} value={name} onChange={e=>{setName(e.target.value);setActive(-1)}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(Math.min(active+1,suggestions.length-1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(Math.max(active-1,0))}if(e.key==='Enter'&&active>=0){e.preventDefault();void add(suggestions[active].name)}if(e.key==='Escape')setSuggestions([])}}/><button type="submit">Lägg till</button></div>{suggestions.length>0&&<ShoppingSuggestions items={suggestions} active={active} onPick={x=>void add(x)}/>}</form><p aria-live="polite" className="shopping-notice">{notice}</p>
 {frequent.length>0&&<section className="shopping-frequent" aria-labelledby="frequent-heading"><h3 id="frequent-heading">Ofta köpt</h3><div>{frequent.map(x=><button key={x.name} onClick={()=>void add(x.name)} type="button">+ {x.name}</button>)}</div></section>}
 <main><h3>Att köpa</h3>{unpurchased.length?<ul className="shopping-items">{unpurchased.map(row)}</ul>:<p>{data.items.length?'Allt på listan är köpt.':'Inköpslistan är tom. Lägg till det du behöver köpa.'}</p>}<details className="shopping-purchased" open={purchasedOpen} onToggle={e=>setPurchasedOpen(e.currentTarget.open)}><summary>Köpta ({purchased.length})</summary>{purchased.length?<ul className="shopping-items">{purchased.map(row)}</ul>:<p>Inga köpta varor ännu.</p>}</details></main><footer><button className="secondary-button" disabled={!data.items.length} onClick={()=>setFinish(true)} type="button">Avsluta inköp</button></footer></div>
 {duplicate&&<div className="shopping-dialog" role="alertdialog" aria-modal="true" aria-labelledby="duplicate-title"><h3 id="duplicate-title">{duplicate.name} {duplicate.item.purchased?'ligger redan under Köpta.':'finns redan på listan.'}</h3>{duplicate.item.purchased?<button ref={duplicateAction} onClick={async()=>{await api.reactivateShoppingItem(duplicate.item.id);closeDuplicate();await reload()}}>Lägg tillbaka på listan</button>:<><button ref={duplicateAction} onClick={async()=>{await api.increaseShoppingItem(duplicate.item.id);closeDuplicate();await reload()}}>Öka antal</button><button onClick={()=>{setDuplicate(null);document.querySelector<HTMLElement>(`[aria-label*="${duplicate.name}"]`)?.focus()}}>Visa varan</button></>}<button onClick={closeDuplicate}>Avbryt</button></div>}
 {finish&&<div className="shopping-dialog" role="alertdialog" aria-modal="true" aria-labelledby="finish-title"><h3 id="finish-title">Avsluta inköp?</h3><p>Köpta varor arkiveras i historiken. Vad vill du göra med varor som är kvar?</p><button onClick={async()=>{await api.finishShopping(true);setFinish(false);await reload();onClose()}}>Behåll oköpta varor</button>{unpurchased.length>0&&<button onClick={async()=>{await api.finishShopping(false);setFinish(false);await reload();onClose()}}>Ta bort oköpta varor</button>}<button onClick={()=>setFinish(false)}>Avbryt</button></div>}</div>
}
