<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BigBrain.Modules/BigBrain.Modules.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="BigBrain.Api.Tests" />
  </ItemGroup>
</Project>
